### ISSUE TITLE
PHP 7 - API - actual error messages not shown when a PHP Error occurs

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#10115]
refs https://github.com/piwik/piwik/issues/10096#issuecomment-215237218 

refs https://github.com/piwik/piwik/issues/8689

**Comment by mattab** [comment]
Also reported in https://github.com/piwik/piwik/issues/10269
```
[Sun Jul 03 18:40:58.230981 2016] [proxy_fcgi:error] [pid 4131] [client 130.0.20.121:59985] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught TypeError: Argument 1 passed to Piwik\API\ResponseBuilder::getResponseException() must be an instance of Exception, instance of Error given, called in /var/www/piwik/core/ExceptionHandler.php on line 90 and defined in /var/www/piwik/core/API/ResponseBuilder.php:130\nStack trace:\n#0 /var/www/piwik/core/ExceptionHandler.php(90): Piwik\API\ResponseBuilder->getResponseException(Object(Error))\n#1 /var/www/piwik/core/ExceptionHandler.php(70): Piwik\ExceptionHandler::getErrorResponse(Object(Error))\n#2 /var/www/piwik/core/ExceptionHandler.php(36): Piwik\ExceptionHandler::dieWithHtmlErrorPage(Object(Error))\n#3 [internal function]: Piwik\ExceptionHandler::handleException(Object(Error))\n#4 {main}\n thrown in /var/www/piwik/core/API/ResponseBuilder.php on line 130\n', referer: /index.php?module=CoreHome&action=index&idSite=1&period=range&date=last7&showaddsite=false
```
