### ISSUE TITLE
Unable to find report 'Insights.getInsights'. 

### ISSUE THREAD

**Issue by d4rken** [piwik/piwik#11489]
Using Piwik `3.0.2`, I'm getting getting this error:
```
Unable to find report 'Insights.getInsights'. 
```
When trying to view my custom variables with the "insights" option selected.
```
strawberry.com/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&category=General_Visitors&subcategory=CustomVariables_CustomVariables&segment=
```

Viewing my custom variables previously worked fine until i selected the insights option. Now I'm stuck and can't switch back.

A bug fix:
- [ ]  Error shouldn't happen

and maybe one UI/UX improvement
- [ ] Even with an error allow switching the options back

would be cool.  Until there is a bugfix, how do i reset the "insights" flag for this view?
```
ERROR 	CoreHome 	2017-03-15 13:39:15 	b9a0f 	Failed to get data from API: Unable to find report 'Insights.getInsights'.
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#14 {main}
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#13 /var/www/piwik/index.php(27): require_once('/var/www/piwik/...')
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#12 /var/www/piwik/core/dispatch.php(34): Piwik\FrontController->dispatch()
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#11 /var/www/piwik/core/FrontController.php(137): Piwik\FrontController->doDispatch('CustomVariables', 'getCustomVariab...', Array)
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#10 /var/www/piwik/core/FrontController.php(542): call_user_func_array(Array, Array)
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#9 [internal function]: Piwik\Plugins\CoreHome\Controller->renderReportWidget(Object(Piwik\Plugins\CustomVariables\Reports\GetCustomVariables))
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#8 /var/www/piwik/plugins/CoreHome/Controller.php(59): Piwik\Plugin\Report->render()
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#7 /var/www/piwik/core/Plugin/Report.php(309): Piwik\Plugin\Visualization->render()
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#6 /var/www/piwik/core/Plugin/Visualization.php(186): Piwik\Plugin\Visualization->applyFilters()
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#5 /var/www/piwik/core/Plugin/Visualization.php(449): Piwik\API\DataTablePostProcessor->process(Object(Piwik\DataTable))
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#4 /var/www/piwik/core/API/DataTablePostProcessor.php(111): Piwik\API\DataTablePostProcessor->applyPivotByFilter(Object(Piwik\DataTable))
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#3 /var/www/piwik/core/API/DataTablePostProcessor.php(161): Piwik\DataTable->filter('Piwik\\DataTable...', Array)
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#2 /var/www/piwik/core/DataTable.php(492): ReflectionClass->newInstanceArgs(Array)
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#1 [internal function]: Piwik\DataTable\Filter\PivotByDimension->__construct(Object(Piwik\DataTable), 'Insights.getIns...', 'CustomVariables...', '', 0, 0)
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	#0 /var/www/piwik/core/DataTable/Filter/PivotByDimension.php(169): Piwik\DataTable\Filter\PivotByDimension->setThisReportMetadata('Insights.getIns...')
ERROR 	CoreHome 	2017-03-15 13:38:12 	99f26 	Failed to get data from API: Unable to find report 'Insights.getInsights'.
```

**Comment by sgiehl** [comment]
You can reset the view option of that report in the piwik_option table. The name should be something like `viewDataTableParameters_username_CustomVariables.getCustomVariables`. Simple remove the entry and it should be resetted.

**Comment by sgiehl** [comment]
Btw. the problem is not the insights itself. Insights would work with this report. But it seems if the table was already pivoted it can't be switched to Insights.

**Comment by d4rken** [comment]
Manual reset worked.

For anyone else having this issue and finding this ticket:

```
mysql> SELECT * FROM piwik_option WHERE option_name like '%getCustomVariables%';
+-----------------------------------------------------------------------------------+----------------------------------------------------------------------- ----------------------------------------------------------------------------------------------------------------------------+----------+
| option_name                                                                       | option_value                                                                                                                                                                                       | autoload |
+-----------------------------------------------------------------------------------+----------------------------------------------------------------------- ----------------------------------------------------------------------------------------------------------------------------+----------+
| viewDataTableParameters_darken_CustomVariables.getCustomVariables                 | {"isFooterExpandedInDashboard":true,"viewDataTable":"insightsVisualiza tion","enable_filter_excludelowpop":"1","filter_sort_column":"","pivotBy":"CustomVariables.CustomVariableValue","flat":"0"} |        0 |
| viewDataTableParameters_darken_CustomVariables.getCustomVariablesValuesFromNameId | {"filter_sort_column":"nb_visits","filter_sort_order":"desc","filter_l imit":"-1"}                                                                                                                 |        0 |
+-----------------------------------------------------------------------------------+----------------------------------------------------------------------- ----------------------------------------------------------------------------------------------------------------------------+----------+
2 rows in set (0.00 sec)

mysql> mysql> SELECT * FROM piwik_option WHERE option_name like 'viewDataTableParameters_darken_CustomVariables.getCustomVariables';
+-------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
| option_name                                                       | option_value                                                                                                                                                                                      | autoload |
+-------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
| viewDataTableParameters_darken_CustomVariables.getCustomVariables | {"isFooterExpandedInDashboard":true,"viewDataTable":"insightsVisualization","enable_filter_excludelowpop":"1","filter_sort_column":"","pivotBy":"CustomVariables.CustomVariableValue","flat":"0"} |        0 |
+-------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+
1 row in set (0.00 sec)
mysql> DELETE FROM piwik_option WHERE option_name = 'viewDataTableParameters_darken_CustomVariables.getCustomVariables';
Query OK, 1 row affected (0.01 sec)
```

Note the `darken` in the variable name which is the target user account.

Also useful [SQL CheatSheet](https://gist.github.com/hofmannsven/9164408).

**Comment by mattab** [comment]
Note this reset is documented in the FAQ here: https://piwik.org/faq/troubleshooting/faq_21433/

**Comment by mattab** [comment]
> But it seems if the table was already pivoted it can't be switched to Insights.

Should our goal in this issue be to prevent Insights visualisation for pivoted reports?

**Comment by sgiehl** [comment]
> Should our goal in this issue be to prevent Insights visualisation for pivoted reports?

Need to investigate if this doesn't work for all reports or only in that special case. Hadn't had time for that yet.

**Comment by sgiehl** [comment]
> Should our goal in this issue be to prevent Insights visualisation for pivoted reports?

Investigated it. Yes we need to prevent that, as it never works.
