### ISSUE TITLE
Session Recordings Datatable broken in Matomo 4.0.x

### ISSUE THREAD

**Issue by ThorbenOermann** [piwik/piwik#16848]
We cannot access our Session Recordings anymore since upgrading Matomo to 4.0.0. The datatable reports an error like "Oops… there was a problem during the request."

I was able to identify the problem by activating the logs:

```log
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] Uncaught exception: Error: Class 'Piwik\Plugins\UserCountry\LocationProvider\GeoIp' not found in /var/www/matomo/plugins/HeatmapSessionRecording/Columns/Metrics/Location.php:76
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] Stack trace:
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #0 /var/www/matomo/plugins/HeatmapSessionRecording/Reports/GetRecordedSessions.php(250): Piwik\Plugins\HeatmapSessionRecording\Columns\Metrics\Location->format()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #1 [internal function]: Piwik\Plugins\HeatmapSessionRecording\Reports\GetRecordedSessions->Piwik\Plugins\HeatmapSessionRecording\Reports\{closure}()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #2 /var/www/matomo/core/DataTable.php(507): call_user_func_array()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #3 /var/www/matomo/core/DataTable.php(613): Piwik\DataTable->filter()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #4 /var/www/matomo/core/API/DataTablePostProcessor.php(303): Piwik\DataTable->applyQueuedFilters()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #5 /var/www/matomo/core/API/DataTablePostProcessor.php(133): Piwik\API\DataTablePostProcessor->applyQueuedFilters()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #6 /var/www/matomo/core/Plugin/Visualization.php(536): Piwik\API\DataTablePostProcessor->process()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #7 /var/www/matomo/core/Plugin/Visualization.php(193): Piwik\Plugin\Visualization->applyFilters()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #8 /var/www/matomo/core/Plugin/Report.php(320): Piwik\Plugin\Visualization->render()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #9 /var/www/matomo/plugins/CoreHome/Controller.php(58): Piwik\Plugin\Report->render()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #10 [internal function]: Piwik\Plugins\CoreHome\Controller->renderReportWidget()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #11 /var/www/matomo/core/FrontController.php(605): call_user_func_array()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #12 /var/www/matomo/core/FrontController.php(166): Piwik\FrontController->doDispatch()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #13 /var/www/matomo/core/dispatch.php(32): Piwik\FrontController->dispatch()
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #14 /var/www/matomo/index.php(25): require_once('/var/www/stack/...')
ERROR Piwik\FrontController[2020-12-01 11:16:46 UTC] [b8603] #15 {main}
```

So I guess the problem is related to the changes made in #15521. 

Using `Piwik\Plugins\GeoIp2\LocationProvider\GeoIp2` instead of `Piwik\Plugins\UserCountry\LocationProvider\GeoIp` fixes the error for us. 

I am sorry if this issue is not supposed to be submited in this repo because Session Recordings are not part of the Matomo Core.

**Comment by Findus23** [comment]
Hi,
Can you please make sure you are using the latest version of the session recordings plugin?

**Comment by ThorbenOermann** [comment]
We are using `v4.0.4` which should be the latest version.

**Comment by sgiehl** [comment]
@ThorbenOermann Thanks for creating the issue. I've fixed the issue in the code. We will release a new version soon. 
ping @tsteur
