### ISSUE TITLE
ComparisonRowGenerator::compareTables() must implement interface Piwik\\DataTable\\DataTableInterface or be null,

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#17641]
refs https://github.com/matomo-org/matomo/issues/17212

saw this error in the logs recently and just want to log it so we can track it if it happens more often in the future.

```
rror: {"message":"Argument 3 passed to Piwik\\Plugins\\API\\Filter\\DataComparisonFilter\\ComparisonRowGenerator::compareTables() must implement interface Piwik\\DataTable\\DataTableInterface or be null, bool given, called in \/var\/www\/html\/plugins\/API\/Filter\/DataComparisonFilter.php on line 224","file":"\/var\/www\/html\/plugins\/API\/Filter\/DataComparisonFilter\/ComparisonRowGenerator.php","line":43,"request_id":"ae84a","backtrace":" on \/var\/www\/html\/plugins\/API\/Filter\/DataComparisonFilter\/ComparisonRowGenerator.php(43)\n#0 \/var\/www\/html\/plugins\/API\/Filter\/DataComparisonFilter.php(224): Piwik\\Plugins\\API\\Filter\\DataComparisonFilter\\ComparisonRowGenerator->compareTables(Array, Object(Piwik\\DataTable\\Map), false)\n#1 \/var\/www\/html\/core\/API\/DataTablePostProcessor.php(489): Piwik\\Plugins\\API\\Filter\\DataComparisonFilter->compare(Object(Piwik\\DataTable\\Map))\n#2 \/var\/www\/html\/core\/API\/DataTablePostProcessor.php(123): Piwik\\API\\DataTablePostProcessor->applyComparison(Object(Piwik\\DataTable\\Map))\n#3 \/var\/www\/html\/core\/Plugin\/Visualization.php(536): Piwik\\API\\DataTablePostProcessor->process(Object(Piwik\\DataTable\\Map))\n#4 \/var\/www\/html\/core\/Plugin\/Visualization.php(193): Piwik\\Plugin\\Visualization->applyFilters()\n#5 \/var\/www\/html\/core\/Plugin\/Controller.php(247): Piwik\\Plugin\\Visualization->render()\n#6 \/var\/www\/html\/plugins\/VisitsSummary\/Controller.php(128): Piwik\\Plugin\\Controller->renderView(Object(Piwik\\Plugins\\CoreVisualizations\\Visualizations\\JqplotGraph\\Evolution))\n#7 [internal function]: Piwik\\Plugins\\VisitsSummary\\Controller->getEvolutionGraph()\n#8 \/var\/www\/html\/core\/FrontController.php(615): call_user_func_array(Array, Array)\n#9 \/var\/www\/html\/core\/FrontController.php(167): Piwik\\FrontController->doDispatch('VisitsSummary', 'getEvolutionGra...', Array)\n#10 \/var\/www\/html\/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#11 \/var\/www\/html\/index.php(25): require_once('\/var\/www\/html\/c...')\n#12 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(615): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(167): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(98): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(138): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(188): Piwik\\FrontController::(Object(TypeError))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}
```

URL: https://$DOMAIN/index.php?date=2021-05-17,2021-06-01&forceView=1&viewDataTable=graphEvolution&module=VisitsSummary&action=getEvolutionGraph&disableLink=0&widget=1&columns%5B%5D=nb_uniq_visitors&columns_to_display%5B%5D=nb_uniq_visitors&comparePeriods%5B%5D=range&compareDates%5B%5D=2021-05-01%2C2021-05-16&idSite=1&period=range

Referrer: https://$DOMAINindex.php?module=CoreHome&action=index&idSite=1&period=range&date=previous30

GET: {"date":"2021-05-17,2021-06-01","forceView":"1","viewDataTable":"graphEvolution","module":"VisitsSummary","action":"getEvolutionGraph","disableLink":"0","widget":"1","columns":["nb_uniq_visitors"],"columns_to_display":["nb_uniq_visitors"],"comparePeriods":["range"],"compareDates":["2021-05-01,2021-05-16"],"idSite":"1","period":"range"}

**Comment by diosmosis** [comment]
@tsteur should be an easy fix: https://github.com/matomo-org/matomo/pull/17642
