### ISSUE TITLE
Unable to register license key

### ISSUE THREAD

**Issue by mttradebyte** [piwik/piwik#19224]
## Expected Behavior

The license key should be added successfully.

## Current Behavior

```
/opt/matomo/console marketplace:set-license-key --license-key=xxxx
ERROR [2022-05-16 12:17:22] 1842135  Uncaught exception: Error: Class 'Piwik\Plugins\Marketplace\Api' not found in /opt/matomo/plugins/Marketplace/Commands/SetLicenseKey.php:40
Stack trace:
#0 /opt/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\Marketplace\Commands\SetLicenseKey->execute()
#1 /opt/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run()
#2 /opt/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand()
#3 [internal function]: Symfony\Component\Console\Application->doRun()
#4 /opt/matomo/core/Console.php(135): call_user_func()
#5 /opt/matomo/core/Access.php(670): Piwik\Console->Piwik\{closure}()
#6 /opt/matomo/core/Console.php(136): Piwik\Access::doAsSuperUser()
#7 /opt/matomo/core/Console.php(87): Piwik\Console->doRunImpl()
#8 /opt/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun()
#9 /opt/matomo/console(32): Symfony\Component\Console\Application->run()
#10 {main}
Uncaught exception in /opt/matomo/plugins/Marketplace/Commands/SetLicenseKey.php line 40:
Class 'Piwik\Plugins\Marketplace\Api' not found
```
## Steps to Reproduce (for Bugs)

1. Run `/path/to/console marketplace:set-license-key --license-key=xxxx`
2. See failure output.

## Context

Unable to add license key, so cannot add addons that we've paid for.

## Your Environment

* Matomo Version: 4.8.0
* PHP Version: 7.4
* Server Operating System: Ubuntu 20.04.03 LTS
* Additionally installed plugins: N/A

* Browser: N/A
* Operating System: N/A

**Comment by mttradebyte** [comment]
Looks like it was fixed in 4.10 https://github.com/matomo-org/matomo/pull/19118, we'll just upgrade.
