### ISSUE TITLE
Illegal offset type Actions.php

### ISSUE THREAD

**Issue by JasonMortonNZ** [piwik/piwik#19589]
Cloud has been noticing an increasing count of the below error `Illegal offset type` for `/plugins/Actions/Actions.php:85`

## Context

**Error:**
```json
{"message":"Illegal offset type","file":"..\/plugins\/Actions\/Actions.php","line":85,"request_id":"6799c","backtrace":" on ..\/plugins\/Actions\/Actions.php(85)\n#0 [internal function]: Piwik\\Plugins\\Actions\\Actions->addReportToInsightsOverview(Array)\n#1 ..\/core\/EventDispatcher.php(141): call_user_func_array(Array, Array)\n#2 ..\/core\/Piwik.php(845): Piwik\\EventDispatcher->postEvent('Insights.addRep...', Array, false, Array)\n#3 ..\/plugins\/Insights\/API.php(67): Piwik\\Piwik::postEvent('Insights.addRep...', Array)\n#4 ..\/plugins\/Insights\/API.php(156): Piwik\\Plugins\\Insights\\API->getOverviewReports()\n#5 ..\/plugins\/Insights\/API.php(145): Piwik\\Plugins\\Insights\\API->generateOverviewReport('getMoversAndSha...', 3, 'range', '2022-07-25,2022...', false, Array)\n#6 ..\/plugins\/Insights\/Controller.php(75): Piwik\\Plugins\\Insights\\API->getMoversAndShakersOverview(3, 'range', '2022-07-25,2022...', false)\n#7 ..\/plugins\/Insights\/Controller.php(41): Piwik\\Plugins\\Insights\\Controller->requestApiReport('getMoversAndSha...')\n#8 [internal function]: Piwik\\Plugins\\Insights\\Controller->getOverallMoversAndShakers()\n#9 ..\/core\/FrontController.php(631): call_user_func_array(Array, Array)\n#10 ..\/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Insights', 'getOverallMover...', Array)\n#11 ..\/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#12 ..\/index.php(25): require_once('..\/c...')\n#13 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(631): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(190): Piwik\\FrontController::(Object(TypeError))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}
```
**URL**: [/index.php?date=2022-07-25,2022-07-31&module=Insights&action=getOverallMoversAndShakers&disableLink=0&widget=1&idSite=3&period=range]()

**Referrer:** [/index.php?module=CoreHome&action=index&date=previous7&period=range&idSite=3]()

**GET:** `{"date":"2022-07-25,2022-07-31","module":"Insights","action":"getOverallMoversAndShakers","disableLink":"0","widget":"1","idSite":"3","period":"range"}`

## Your Environment

* Matomo Version: 4.10.0
* PHP Version: 8.0
* Server Operating System: Linux
* Additionally installed plugins:

**Comment by sgiehl** [comment]
Looking at the code I can't see any reason why that could happen. The method is triggered by an event, that passes through an array reference. The method itself tries to add an element to that array. I don't have a clue why that could cause an illegal offset type 🤷

**Comment by justinvelluppillai** [comment]
@JasonMortonNZ let us know if this is resolved by the translations fix and we can close this.

**Comment by JasonMortonNZ** [comment]
@justinvelluppillai Yes, this is now resolved by the translations fix 👍
