### ISSUE TITLE
User Invite doesn't work when using other Login plugins

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#19664]
When using other Login plugins (Such as the LoginLdap plugin) the default Login plugin is automatically disabled.
In these cases the User Invite feature throws the following error:
```
The plugin Login is not enabled. You can activate the plugin on Settings > Plugins page in Matomo.

#0 /matomo4/core/FrontController.php(599): Piwik\FrontController->prepareDispatch('Login', 'acceptInvitatio...', Array)
#1 /matomo4/core/FrontController.php(169): Piwik\FrontController->doDispatch(NULL, NULL, NULL)
#2 /matomo4/core/dispatch.php(32): Piwik\FrontController->dispatch()
#3 /matomo4/index.php(25): require_once('/matomo4...')
#4 {main}
```

**Comment by peterhashair** [comment]
@Starker3 thank you for reporting this, we are aware of this bug, the plugin team will review this.
