### ISSUE TITLE
Fatal error "urldecode(): Argument #1 ($string) must be of type string, array given" in API.getBulkRequest

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20157]
See below details 

> Error: {"message":"urldecode(): Argument #1 ($string) must be of type string, array given","file":"plugins\/API\/API.php","line":459,"request_id":"1e6ed","backtrace":" on plugins\/API\/API.php(459)\n#0 [internal function]: urldecode(Array)\n#1 plugins\/API\/API.php(459): array_map('urldecode', Array)\n#2 [internal function]: Piwik\\Plugins\\API\\API->getBulkRequest(Array)\n#3 core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#4 core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#5 core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#6 core\/API\/Request.php(267): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getBulkRequest', Array)\n#7 plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#8 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#9 core\/FrontController.php(631): call_user_func_array(Array, Array)\n#10 core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#11 core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#12 index.php(25): require_once('c...')\n#13 {main}"

> URL: ?module=API&method=API.getBulkRequest&urls%5B0%5D%5BidSite%5D=5&format=JSON&token_auth=XYZANONYMIZED&urls%5B0%5D%5Bmethod%5D=Actions.getPageUrls&urls%5B0%5D%5Bperiod%5D=day&urls%5B0%5D%5Bdate%5D=today&urls%5B1%5D%5Bmethod%5D=UserCountry.getCountry&urls%5B1%5D%5Bperiod%5D=day&urls%5B1%5D%5Bdate%5D=today&urls%5B2%5D%5Bmethod%5D=DevicesDetection.getOsFamilies&urls%5B2%5D%5Bperiod%5D=day&urls%5B2%5D%5Bdate%5D=today&urls%5B1%5D%5BidSite%5D=5&urls%5B2%5D%5BidSite%5D=5

> GET: {"module":"API","method":"API.getBulkRequest","urls":[{"idSite":"5","method":"Actions.getPageUrls","period":"day","date":"today"},{"method":"UserCountry.getCountry","period":"day","date":"today","idSite":"5"},{"method":"DevicesDetection.getOsFamilies","period":"day","date":"today","idSite":"5"}],"format":"JSON","token_auth":"XYZANONYMIZED","filter_limit":100}

**Comment by sgiehl** [comment]
Seems the provided value for urls does not have an expected value. It should be an array of query strings. In that case it is already an array of request arrays. 
We could add some sort of filter on that input variable to sort our all values that are not of type string maybe.
Or should we support providing such request arrays?
Do you know where that request came from? Was it hand crafted by the user, or did some of our code produce it?

**Comment by tsteur** [comment]
> Do you know where that request came from? Was it hand crafted by the user, or did some of our code produce it?

I don't know unfortunately. It looks though like this library was maybe involved: https://github.com/axios/axios

> Or should we support providing such request arrays?

I don't have any strong preference. I guess if it's easy to do, it could be quite nice to support it since it provides more flexibility for the user. It's not needed though. If we don't support it, then it be just important that we don't let it fail silently with a 2XX error code but we need to make sure there's eg a `400 (Bad Request)` response or so. It may be hard to troubleshoot though for users so supporting arrays could be good
