### ISSUE TITLE
Fatal error: Division by zero in Visualizations/Cloud.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20384]
See below details. Latest Matomo version with PHP 8

> Error: {"message":"Division by zero","file":"plugins\/CoreVisualizations\/Visualizations\/Cloud.php","line":197,"request_id":"6a795","backtrace":" on plugins\/CoreVisualizations\/Visualizations\/Cloud.php(197)\n#0 plugins\/CoreVisualizations\/Visualizations\/Cloud.php(117): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Cloud->getPercentage('0,5\\xC2\\xA0%', '0,5\\xC2\\xA0%')\n#1 plugins\/CoreVisualizations\/Visualizations\/Cloud.php(78): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Cloud->getCloudValues()\n#2 core\/Plugin\/Visualization.php(195): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Cloud->afterAllFiltersAreApplied()\n#3 core\/Plugin\/Report.php(320): Piwik\\Plugin\\Visualization->render()\n#4 plugins\/CustomReports\/GetCustomReport.php(105): Piwik\\Plugin\\Report->render()\n#5 plugins\/CoreHome\/Controller.php(60): Piwik\\Plugins\\CustomReports\\GetCustomReport->render()\n#6 [internal function]: Piwik\\Plugins\\CoreHome\\Controller->renderReportWidget(Object(Piwik\\Plugins\\CustomReports\\GetCustomReport))\n#7 core\/FrontController.php(637): call_user_func_array(Array, Array)\n#8 core\/FrontController.php(169): Piwik\\FrontController->doDispatch('CustomReports', 'getCustomReport', Array)\n#9 core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#10 index.php(25): require_once('c...')\n#11 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(196): Piwik\\FrontController::(Object(DivisionByZeroError))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

> URL: /index.php?segment=referrerType%3D%3Dsearch&date=2023-01-30,2023-02-19&viewDataTable=cloud&module=CustomReports&action=getCustomReport&idCustomReport=2&disableLink=0&widget=1&comparePeriods%5B%5D=range&compareDates%5B%5D=2023-01-09%2C2023-01-29&idSite=2&period=range

> Referrer: /index.php?module=CoreHome&action=index&idSite=2&period=day&date=yesterday

> GET: {"segment":"referrerType==search","date":"2023-01-30,2023-02-19","viewDataTable":"cloud","module":"CustomReports","action":"getCustomReport","idCustomReport":"2","disableLink":"0","widget":"1","comparePeriods":["range"],"compareDates":["2023-01-09,2023-01-29"],"idSite":"2","period":"range"}

**Comment by sgiehl** [comment]
@tsteur looking at the backtrace it seems the custom report is trying to show the cloud viz for a percentage metric, causing the calculation to fail:
```
plugins/CoreVisualizations/Visualizations/Cloud.php(117): Piwik\Plugins\CoreVisualizations\Visualizations\Cloud->getPercentage('0,5\xC2\xA0%', '0,5\xC2\xA0%')
```
There might currently be no proper fix for this one. We would actually need to fetch the metrics unformatted for the cloud viz, but that would currently mean that percentage metrics would be shown as float values.
It's a similar problem like here: https://github.com/matomo-org/matomo/issues/19940#issuecomment-1308803094
