### ISSUE TITLE
Matomo 5: Log Action Join performance improvement causing issues with Custom Reports

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20530]
## Context
We recently merged: https://github.com/matomo-org/matomo/pull/20379

We ran this on a Matomo 4 instance and noticed there is a regression / incompatibility with Custom Reports see below error:

```
> [2023-03-29 07:19:38] piwik.DEBUG: SELECT /*+ MAX_EXECUTION_TIME(7200000) */ /*+ MAX_EXECUTION_TIME(2700000) */ CASE WHEN counter = 50001 THEN '__mtm_ranking_query_others__' ELSE `Actions.PageTitle` END AS `Actions.PageTitle` , `pageviews` FROM ( SELECT `Actions.PageTitle`, CASE WHEN @counter = 50001 THEN 50001 ELSE @counter:=@counter+1 END AS counter , `pageviews` FROM ( SELECT @counter:=0 ) initCounter, ( SELECT /* CustomReports */ /* segmenthash 7a3ac7a007ef7cd464d20eec6b3daec3 */ /* sites 1 */ /* 2023-03-28,2023-03-29 */ /* CustomReports */ /* trigger = CronArchive */ log_inner.name AS 'Actions.PageTitle', count(distinct log_inner.idlink_va) AS 'pageviews' FROM ( SELECT log_action_idaction_name.name, log_link_visit_action.idlink_va FROM logtmpsegment35186a255eb5cc825651f342cb19ef6d AS logtmpsegment35186a255eb5cc825651f342cb19ef6d INNER JOIN log_link_v
isit_action AS log_link_visit_action ON log_link_visit_action.idvisit = logtmpsegment35186a255eb5cc825651f342cb19ef6d.idvisit LEFT JOIN log_action AS log_action_idaction_name ON log_link_visit_action.idaction_name = log_action_idaction_name.idaction RIGHT JOIN log_visit AS log_visit ON log_visit.idvisit = logtmpsegment35186a255eb5cc825651f342cb19ef6d.idvisit LEFT JOIN log_action AS log_action ON log_link_visit_action.idaction_url = log_action.idaction WHERE (( log_action_idaction_name.name is not null AND log_action_idaction_name.type = "4" AND log_action.type = "1" ) AND ( (log_action_segment_log_link_visit_actionidaction_name.name LIKE ? AND log_action_segment_log_link_visit_actionidaction_name.type = '4') )) GROUP BY log_action_idaction_name.name, `log_link_visit_action`.`idlink_va` ORDER BY NULL ) AS log_inner GROUP BY log_inner.name ORDER BY pageviews ) actualQuery ) AS withCounter GROUP BY counter [] {"class":"CustomReports","r
equest_id":"23651 sandbox.staging.dev.matomo.cloud"}
> {"result":"error","message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_action_segment_log_link_visit_actionidaction_name.name' in 'where clause' - in plugin CustomReports. #0 \/core\/ArchiveProcessor\/Loader.php(288): Piwik\\ArchiveProcessor\\PluginsArchiver->callAggregateAllPlugins('2', '1', false) #1 \/core\/ArchiveProcessor\/Loader.php(180): Piwik\\ArchiveProcessor\\Loader->prepareAllPluginsArchive('2', '1') #2 \/core\/ArchiveProcessor\/Loader.php(163): Piwik\\ArchiveProcessor\\Loader->insertArchiveData('1', '1') #3 \/core\/ArchiveProcessor\/Loader.php(103): Piwik\\ArchiveProcessor\\Loader->prepareArchiveImpl('VisitsSummary') #4 \/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader->Piwik\\ArchiveProcessor\\{closure}() #5 \/core\/ArchiveProcessor\/Loader.php(107): Piwik\\Context::changeIdSite(1, Object(Closure)) #6 \/plugins\/CoreAdmin
Home\/API.php(294): Piwik\\ArchiveProcessor\\Loader->prepareArchive('VisitsSummary') #7 \/core\/Archive.php(894): Piwik\\Plugins\\CoreAdminHome\\API->archiveReports(1, Object(Piwik\\Period\\Day), '2023-03-29', 'city%3D%3DBosto...', 'VisitsSummary', '') #8 \/core\/Archive.php(686): Piwik\\Archive->prepareArchive(Array, Object(Piwik\\Site), Object(Piwik\\Period\\Day)) #9 \/core\/Archive.php(624): Piwik\\Archive->cacheArchiveIdsAfterLaunching(Array, Array) #10 \/core\/Archive.php(549): Piwik\\Archive->getArchiveIds(Array) #11 \/core\/Archive.php(347): Piwik\\Archive->get(Array, 'numeric') #12 \/core\/ArchiveProcessor.php(630): Piwik\\Archive->getDataTableFromNumeric(Array) #13 \/core\/ArchiveProcessor.php(265): Piwik\\ArchiveProcessor->getAggregatedNumericMetrics(Array, false) #14 \/core\/ArchiveProcessor\/PluginsArchiver.php(311): Piwi
k\\ArchiveProcessor->aggregateNumericMetrics(Array) #15 \/core\/ArchiveProcessor\/PluginsArchiver.php(109): Piwik\\ArchiveProcessor\\PluginsArchiver->aggregateMultipleVisitsMetrics() #16 \/core\/ArchiveProcessor\/Loader.php(282): Piwik\\ArchiveProcessor\\PluginsArchiver->callAggregateCoreMetrics() #17 \/core\/ArchiveProcessor\/Loader.php(180): Piwik\\ArchiveProcessor\\Loader->prepareAllPluginsArchive('87', '28') #18 \/core\/ArchiveProcessor\/Loader.php(163): Piwik\\ArchiveProcessor\\Loader->insertArchiveData('87', '28') #19 \/core\/ArchiveProcessor\/Loader.php(103): Piwik\\ArchiveProcessor\\Loader->prepareArchiveImpl('VisitsSummary') #20 \/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader->Piwik\\ArchiveProcessor\\{closure}() #21 \/core\/ArchiveProcessor\/Loader.php(107): Piwik\\Context::changeIdSite(1, Object(Closure)) #22 \/plugi
ns\/CoreAdminHome\/API.php(294): Piwik\\ArchiveProcessor\\Loader->prepareArchive('VisitsSummary') #23 \/core\/Archive.php(894): Piwik\\Plugins\\CoreAdminHome\\API->archiveReports(1, Object(Piwik\\Period\\Month), '2023-03-01', 'city%3D%3DBosto...', 'VisitsSummary', '') #24 \/core\/Archive.php(686): Piwik\\Archive->prepareArchive(Array, Object(Piwik\\Site), Object(Piwik\\Period\\Month)) #25 \/core\/Archive.php(624): Piwik\\Archive->cacheArchiveIdsAfterLaunching(Array, Array) #26 \/core\/Archive.php(549): Piwik\\Archive->getArchiveIds(Array) #27 \/core\/Archive.php(347): Piwik\\Archive->get(Array, 'numeric') #28
``` 
## Expected Behavior

Archiving works as expected.

## Current Behavior

Archiving isn't working.

## Steps to Reproduce (for Bugs)

I may be wrong but I believe there is this segment:

```sql
INSERT INTO `segment` (`idsegment`, `name`, `definition`, `hash`, `login`, `enable_all_users`, `enable_only_idsite`, `auto_archive`, `ts_created`, `ts_last_edit`, `deleted`)
VALUES
	(23, 'Boston', 'city==Boston', '7a3ac7a007ef7cd464d20eec6b3daec3', 'test', 1, 1, 1, '2023-03-28 22:49:05', NULL, 0);
```

and this custom report:

```sql
INSERT INTO `custom_reports` (`idcustomreport`, `idsite`, `revision`, `report_type`, `name`, `description`, `category`, `subcategory`, `dimensions`, `metrics`, `segment_filter`, `created_date`, `updated_date`, `status`)
VALUES
	(2, 1, 0, 'table', 'Bali pages, breakdown new/returning', '', 'CustomReports_CustomReports', '', '[\"Actions.PageTitle\",\"CoreHome.VisitorReturning\"]', '[\"nb_uniq_visitors\",\"pageviews\",\"nb_visits\"]', 'pageTitle=@bali', '2017-10-20 02:41:08', '2017-10-20 02:41:08', 'active');
```

Then launch archiving (not confirmed)

**Comment by diosmosis** [comment]
@tsteur Not able to reproduce this locally (on matomo 5 or a patched matomo 4). Looking at the SQL, the extra join is not added, which would suggest `$segmentObject->dimension && $segmentObject->dimension->getDbColumnJoin()` for the CustomReports filter, so I'm wondering if it's a random caching issue. Still looking into it.

**Comment by diosmosis** [comment]
Ok, nevermind, I can reproduce now, I had a wrong metric in.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/difference-matomo-dashboard-and-email-reports/50556/10
