### ISSUE TITLE
Fatal error: count(): Argument #1 ($value) must be of type Countable|array, float in Renderer/Xml.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20586]
See error report below that was experienced on Cloud using Matomo 4.13.3

Error: {"message":"count(): Argument #1 ($value) must be of type Countable|array, float given","file":"core\/DataTable\/Renderer\/Xml.php","line":251,"request_id":"93701","backtrace":" on core\/DataTable\/Renderer\/Xml.php(251)\n#0 core\/DataTable\/Renderer\/Xml.php(251): count(10)\n#1 core\/DataTable\/Renderer\/Xml.php(171): Piwik\\DataTable\\Renderer\\Xml->renderDataTableMap(Object(Piwik\\DataTable\\Map), Array, '\\t')\n#2 core\/DataTable\/Renderer\/Xml.php(101): Piwik\\DataTable\\Renderer\\Xml->renderArray(Array, '\\t')\n#3 core\/DataTable\/Renderer\/Xml.php(35): Piwik\\DataTable\\Renderer\\Xml->renderTable(Array)\n#4 core\/API\/ApiRenderer.php(77): Piwik\\DataTable\\Renderer\\Xml->render()\n#5 core\/API\/ResponseBuilder.php(236): Piwik\\API\\ApiRenderer->renderArray(Array)\n#6 core\/API\/ResponseBuilder.php(113): Piwik\\API\\ResponseBuilder->handleArray(Array)\n#7 core\/API\/Request.php(273): Piwik\\API\\ResponseBuilder->getResponse(Array, 'API', 'getProcessedRep...')\n#8 core\/Context.php(28): Piwik\\API\\Request->Piwik\\API\\{closure}()\n#9 core\/API\/Request.php(274): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#10 plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#11 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#12 core\/FrontController.php(637): call_user_func_array(Array, Array)\n#13 core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#14 core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#15 index.php(25): require_once('c...')\n#16 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(196): Piwik\\FrontController::(Object(TypeError))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

URL: /index.php?module=API&format=XML&idSite=1&period=day&date=2023-02-13,2023-04-13&method=API.getProcessedReport&apiModule=CustomReports&apiAction=getCustomReport&idCustomReport=1&reportUniqueId=CustomReports_getCustomReport_idCustomReport--1&filter_limit=100&format_metrics=1&expanded=1&token_auth=XYZANONYMIZED&force_api_session=1

Referrer: /index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday

GET: {"module":"API","format":"XML","idSite":"1","period":"day","date":"2023-02-13,2023-04-13","method":"API.getProcessedReport","apiModule":"CustomReports","apiAction":"getCustomReport","idCustomReport":"1","reportUniqueId":"CustomReports_getCustomReport_idCustomReport--1","filter_limit":"100","format_metrics":"1","expanded":"1","token_auth":"XYZANONYMIZED","force_api_session":"1"}

**Comment by bx80** [comment]
From a quick look at this, my guess is that `renderDataTableMap()` is detecting a `case 1` array as a `case 2` array and then incorrectly trying to `count()` a scalar value. The issue might be data specific and will need further investigation as it might be difficult to recreate without the custom report definition.
