### ISSUE TITLE
Fatal error: Call to a member function getColumns() on bool in Visualization.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20615]
See crash information below. Happening on latest Matomo.

> Error: {"message":"Call to a member function getColumns() on bool","file":"core\/Plugin\/Visualization.php","line":431,"request_id":"757a9","backtrace":" on core\/Plugin\/Visualization.php(431)\n#0 core\/Plugin\/Visualization.php(189): Piwik\\Plugin\\Visualization->postDataTableLoadedFromAPI()\n#1 core\/Plugin\/Controller.php(258): Piwik\\Plugin\\Visualization->render()\n#2 plugins\/VisitsSummary\/Controller.php(126): Piwik\\Plugin\\Controller->renderView(Object(Piwik\\Plugins\\CoreVisualizations\\Visualizations\\JqplotGraph\\Evolution))\n#3 [internal function]: Piwik\\Plugins\\VisitsSummary\\Controller->getEvolutionGraph()\n#4 core\/FrontController.php(637): call_user_func_array(Array, Array)\n#5 core\/FrontController.php(169): Piwik\\FrontController->doDispatch('VisitsSummary', 'getEvolutionGra...', Array)\n#6 core\/FrontController.php(216): Piwik\\FrontController->dispatch('VisitsSummary', 'getEvolutionGra...', NULL)\n#7 plugins\/Widgetize\/Controller.php(88): Piwik\\FrontController->fetchDispatch('VisitsSummary', 'getEvolutionGra...')\n#8 [internal function]: Piwik\\Plugins\\Widgetize\\Controller->iframe()\n#9 core\/FrontController.php(637): call_user_func_array(Array, Array)\n#10 core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Widgetize', 'iframe', Array)\n#11 core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#12 index.php(25): require_once('c...')\n#13 {main}","safemode_backtrace":"#0 [internal function]: 

URL: https://demo.matomo.cloud/?action=iframe&actionToWidgetize=getEvolutionGraph&columns%5B%5D=https%3A%2F%2Fwww.google.com%2Fmi%2F&date=2009-05-18&disableLink=1&idSite=1&module=Widgetize&moduleToWidgetize=VisitsSummary&period=day

Referrer: http://demo.matomo.cloud?action=iframe&actionToWidgetize=getEvolutionGraph&columns%5B%5D=https%3A%2F%2Fwww.google.com%2Fmi%2F&date=2009-05-18&disableLink=1&idSite=1&module=Widgetize&moduleToWidgetize=VisitsSummary&period=day

GET: {"action":"iframe","actionToWidgetize":"getEvolutionGraph","columns":["https:\/\/www.google.com\/mi\/"],"date":"2009-05-18","disableLink":"1","idSite":"1","module":"Widgetize","moduleToWidgetize":"VisitsSummary","period":"day"}

**Comment by michalkleiner** [comment]
Hi @tsteur,

thank you for the report. I was able to replicate this locally so will pass this to the queue for prioritisation.
