### ISSUE TITLE
Fatal error: Report::getProcessedMetricsForTable(): Argument #1 ($dataTable) must be of type Piwik\DataTable, Piwik\DataTable\Map given

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21065]
See details below. I don't have more information.

> Error: {"message":"Piwik\\Plugin\\Report::getProcessedMetricsForTable(): Argument #1 ($dataTable) must be of type Piwik\\DataTable, Piwik\\DataTable\\Map given, called in plugins\/CoreVisualizations\/Visualizations\/Sparklines.php on line 163","file":"core\/Plugin\/Report.php","line":1101,"request_id":"74b68","backtrace":" on core\/Plugin\/Report.php(1101)\n#0 plugins\/CoreVisualizations\/Visualizations\/Sparklines.php(163): Piwik\\Plugin\\Report::getProcessedMetricsForTable(Object(Piwik\\DataTable\\Map), Object(Piwik\\Plugins\\API\\Reports\\Get))\n#1 plugins\/CoreVisualizations\/Visualizations\/Sparklines.php(108): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Sparklines->fetchConfiguredSparklines()\n#2 core\/Plugin\/Report.php(344): Piwik\\Plugins\\CoreVisualizations\\Visualizations\\Sparklines->render()\n#3 plugins\/CoreHome\/Controller.php(60): Piwik\\Plugin\\Report->render()\n#4 [internal function]: Piwik\\Plugins\\CoreHome\\Controller->renderReportWidget(Object(Piwik\\Plugins\\VisitsSummary\\Reports\\Get))\n#5 core\/FrontController.php(637): call_user_func_array(Array, Array)\n#6 core\/FrontController.php(169): Piwik\\FrontController->doDispatch('VisitsSummary', 'get', Array)\n#7 core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#8 index.php(25): 

> URL: /index.php?date=previous7&module=VisitsSummary&format=html&forceView=1&viewDataTable=sparklines&action=get&widget=1&containerId=VisitOverviewWithGraph&period=week&idSite=1&segment=&showtitle=1&random=4564

> Referrer: /index.php?module=CoreHome&action=index&idSite=1&period=range&date=previous7

> GET: {"date":"previous7","module":"VisitsSummary","format":"html","forceView":"1","viewDataTable":"sparklines","action":"get","widget":"1","containerId":"VisitOverviewWithGraph","period":"week","idSite":"1","segment":"","showtitle":"1","random":"4564"}

**Comment by michalkleiner** [comment]
For some reason an API response for getting the `DataTable` returned a `Map` (an array of `DataTable`s) instead of a single one. Will try to replicate the query as I don't think ensuring we use the first one in case of receiving an array is the right approach. Best to solve the cause rather than hide the symptoms.

**Comment by michalkleiner** [comment]
Was able to get an error with the same query string on demo.matomo.cloud.
