### ISSUE TITLE
Matomo 5 regression making archiving fail: Metrics::makeGoalColumnsRow(): Argument #1 ($idGoal) must be of type int in CustomDimension.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21344]
This fatal error happened on 5.0.0-rc4

> Error: {"message":"Piwik\\Metrics::makeGoalColumnsRow(): Argument #1 ($idGoal) must be of type int, string given, called in \/plugins\/CustomDimensions\/RecordBuilders\/CustomDimension.php on line 143","file":"\/core\/Metrics.php","line":613,"request_id":"dcc10","backtrace":" on \/core\/Metrics.php(613)\n#0 \/plugins\/CustomDimensions\/RecordBuilders\/CustomDimension.php(143): Piwik\\Metrics::makeGoalColumnsRow('__mtm_ranking_q...', Array)\n#1 \/plugins\/CustomDimensions\/RecordBuilders\/CustomDimension.php(75): Piwik\\Plugins\\CustomDimensions\\RecordBuilders\\CustomDimension->aggregateFromConversions(Object(Piwik\\DataTable), Object(Piwik\\DataAccess\\LogAggregator), 'custom_dimensio...', Array, ' log_conversion...')\n#2 \/core\/ArchiveProcessor\/RecordBuilder.php(94): Piwik\\Plugins\\CustomDimensions\\RecordBuilders\\CustomDimension->aggregate(Object(Piwik\\ArchiveProcessor))\n#3 \/core\/Plugin\/Archiver.php(205): Piwik\\ArchiveProcessor\\RecordBuilder->buildFromLogs(Object(Piwik\\ArchiveProcessor))\n#4 \/core\/ArchiveProcessor\/PluginsArchiver.php(181): Piwik\\Plugin\\Archiver->callAggregateDayReport()\n#5 \/core\/ArchiveProcessor\/Loader.php(310): Piwik\\ArchiveProcessor\\PluginsArchiver->callAggregateAllPlugins(27143, '21037', false)\n#6 \/core\/ArchiveProcessor\/Loader.php(185): Piwik\\ArchiveProcessor\\Loader->prepareAllPluginsArchive(27143, '21037')\n#7 \/core\/ArchiveProcessor\/Loader.php(164): Piwik\\ArchiveProcessor\\Loader->insertArchiveData(27090.0, 21002.0, false, NULL)\n#8 \/core\/ArchiveProcessor\/Loader.php(104): Piwik\\ArchiveProcessor\\Loader->prepareArchiveImpl('VisitsSummary')\n#9 \/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader->Piwik\\ArchiveProcessor\\{closure}()\n#10 \/core\/ArchiveProcessor\/Loader.php(108): Piwik\\Context::changeIdSite(2, Object(Closure))\n#11 \/plugins\/CoreAdminHome\/API.php(295): Piwik\\ArchiveProcessor\\Loader->prepareArchive('VisitsSummary')\n#12 \/core\/Archive.php(918): Piwik\\Plugins\\CoreAdminHome\\API->archiveReports(2, Object(Piwik\\Period\\Day), '2023-10-02', '', 'VisitsSummary', '')\n#13 \/core\/Archive.php(699): Piwik\\Archive->prepareArchive(Array, Object(Piwik\\Site), Object(Piwik\\Period\\Day))\n#14 \/core\/Archive.php(638): Piwik\\Archive->cacheArchiveIdsAfterLaunching(Array)\n#15 \/core\/Archive.php(564): Piwik\\Archive->getArchiveIds(Array)\n#16 \/core\/Archive.php(361): Piwik\\Archive->get(Array, 'numeric')\n#17 \/core\/ArchiveProcessor.php(700): Piwik\\Archive->getDataTableFromNumeric(Array)\n#18 \/core\/ArchiveProcessor.php(282): Piwik\\ArchiveProcessor->getAggregatedNumericMetrics(Array, false)\n#19 \/core\/ArchiveProcessor\/PluginsArchiver.php(327): Piwik\\ArchiveProcessor->aggregateNumericMetrics(Array)\n#20 \/core\/ArchiveProcessor\/PluginsArchiver.php(109): Piwik\\ArchiveProcessor\\PluginsArchiver->aggregateMultipleVisitsMetrics()\n#21 \/core\/ArchiveProcessor\/Loader.php(304): Piwik\\ArchiveProcessor\\PluginsArchiver->callAggregateCoreMetrics()\n#22 \/core\/ArchiveProcessor\/Loader.php(185): Piwik\\ArchiveProcessor\\Loader->prepareAllPluginsArchive(14674.0, 11317.0)\n#23 \/core\/ArchiveProcessor\/Loader.php(164): Piwik\\ArchiveProcessor\\Loader->insertArchiveData(14674.0, 11317.0, false, NULL)\n#24 \/core\/ArchiveProcessor\/Loader.php(104): Piwik\\ArchiveProcessor\\Loader->prepareArchiveImpl('VisitsSummary')\n#25 \/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader->Piwik\\ArchiveProcessor\\{closure}()\n#26 \/core\/ArchiveProcessor\/Loader.php(108): Piwik\\Context::changeIdSite(2, Object(Closure))\n#27 \/plugins\/CoreAdminHome\/API.php(295): Piwik\\ArchiveProcessor\\Loader->prepareArchive('VisitsSummary')\n#28 \/core\/Archive.php(918): Piwik\\Plugins\\CoreAdminHome\\API->archiveReports(2, Object(Piwik\\Period\\Week), '2023-10-02', '', 'VisitsSummary', '')\n#29 \/core\/Archive.php(699): Piwik\\Archive->prepareArchive(Array, Object(Piwik\\Site), Object(Piwik\\Period\\Week))\n#30 \/core\/Archive.php(638): Piwik\\Archive->cacheArchiveIdsAfterLaunching(Array)\n#31 \/core\/Archive.php(564): Piwik\\Archive->getArchiveIds(Array)\n#32 \/core\/Archive.php(361): Piwik\\Archive->get(Array, 'numeric')\n#33 \/core\/ArchiveProcessor.php(700): Piwik\\Archive->getDataTableFromNumeric(Array)\n#34 \/core\/ArchiveProcessor.php(282): Piwik\\ArchiveProcessor->getAggregatedNumericMetrics(Array, false)\n#35 \/core\/ArchiveProcessor\/PluginsArchiver.php(327): Piwik\\ArchiveProcessor->aggregateNumericMetrics(Array)\n#36 \/core\/ArchiveProcessor\/PluginsArchiver.php(109): Piwik\\ArchiveProcessor\\PluginsArchiver->aggregateMultipleVisitsMetrics()\n#37 \/core\/ArchiveProcessor\/Loader.php(304): Piwik\\ArchiveProcessor\\PluginsArchiver->callAggregateCoreMetrics()\n#38 \/core\/ArchiveProcessor\/Loader.php(185): Piwik\\ArchiveProcessor\\Loader->prepareAllPluginsArchive(35120.0, 27017.0)\n#39 \/core\/ArchiveProcessor\/Loader.php(164): Piwik\\ArchiveProcessor\\Loader->insertArchiveData(35120.0, 27017.0, false, NULL)\n#40 \/core\/ArchiveProcessor\/Loader.php(104): Piwik\\ArchiveProcessor\\Loader->prepareArchiveImpl('VisitsSummary')\n#41 \/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader->Piwik\\ArchiveProcessor\\{closure}()\n#42 \/core\/ArchiveProcessor\/Loader.php(108): Piwik\\Context::changeIdSite(2, Object(Closure))\n#43 \/plugins\/CoreAdminHome\/API.php(295): Piwik\\ArchiveProcessor\\Loader->prepareArchive('VisitsSummary')\n#44 \/core\/Archive.php(918): Piwik\\Plugins\\CoreAdminHome\\API->archiveReports(2, Object(Piwik\\Period\\Month), '2023-10-01', '', 'VisitsSummary', '')\n#45 \/core\/Archive.php(699): Piwik\\Archive->prepareArchive(Array, Object(Piwik\\Site), Object(Piwik\\Period\\Month))\n#46 \/core\/Archive.php(638): Piwik\\Archive->cacheArchiveIdsAfterLaunching(Array)\n#47 \/core\/Archive.php(564): Piwik\\Archive->getArchiveIds(Array)\n#48 \/core\/Archive.php(361): Piwik\\Archive->get(Array, 'numeric')\n#49 \/core\/ArchiveProcessor.php(700): Piwik\\Archive->getDataTableFromNumeric(Array)\n#50 \/core\/ArchiveProcessor.php(282): Piwik\\ArchiveProcessor->getAggregatedNumericMetrics(Array, false)\n#51 \/core\/ArchiveProcessor\/PluginsArchiver.php(327): Piwik\\ArchiveProcessor->aggregateNumericMetrics(Array)\n#52 \/core\/ArchiveProcessor\/PluginsArchiver.php(109): Piwik\\ArchiveProcessor\\PluginsArchiver->aggregateMultipleVisitsMetrics()\n#53 \/core\/ArchiveProcessor\/Loader.php(304): Piwik\\ArchiveProcessor\\PluginsArchiver->callAggregateCoreMetrics()\n#54 \/core\/ArchiveProcessor\/Loader.php(185): Piwik\\ArchiveProcessor\\Loader->prepareAllPluginsArchive(8092946.0, 5981698.0)\n#55 \/core\/ArchiveProcessor\/Loader.php(164): Piwik\\ArchiveProcessor\\Loader->insertArchiveData(8092946.0, 5981698.0, false, NULL)\n#56 \/core\/ArchiveProcessor\/Loader.php(104): Piwik\\ArchiveProcessor\\Loader->prepareArchiveImpl(false)\n#57 \/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader->Piwik\\ArchiveProcessor\\{closure}()\n#58 \/core\/ArchiveProcessor\/Loader.php(108): Piwik\\Context::changeIdSite(2, Object(Closure))\n#59 \/plugins\/CoreAdminHome\/API.php(295): Piwik\\ArchiveProcessor\\Loader->prepareArchive(false)\n#60 [internal function]: Piwik\\Plugins\\CoreAdminHome\\API->archiveReports('2', Object(Piwik\\Period\\Year), '2023-01-01', false, false, false)\n#61 \/core\/API\/Proxy.php(255): call_user_func_array(Array, Array)\n#62 \/core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#63 \/core\/API\/Proxy.php(346): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#64 \/core\/API\/Request.php(272): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'archiveReports', Array)\n#65 \/plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#66 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#67 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#68 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#69 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#70 \/index.php(25): require_once('\/c...')\n#71 \/core\/CliMulti\/RequestCommand.php(75): require_once('\/i...')\n#72 \/core\/Plugin\/ConsoleCommand.php(110): Piwik\\CliMulti\\RequestCommand->doExecute()\n#73 \/vendor\/symfony\/console\/Command\/Command.php(298): Piwik\\Plugin\\ConsoleCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#74 \/core\/Plugin\/ConsoleCommand.php(125): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#75 \/vendor\/symfony\/console\/Application.php(1040): Piwik\\Plugin\\ConsoleCommand->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#76 \/vendor\/symfony\/console\/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand(Object(Piwik\\CliMulti\\RequestCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#77 \/core\/Console.php(106): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#78 [internal function]: Piwik\\Console->originDoRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#79 \/core\/Console.php(145): call_user_func(Array, Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#80 \/core\/Access.php(670): Piwik\\Console->Piwik\\{closure}()\n#81 \/core\/Console.php(146): Piwik\\Access::doAsSuperUser(Object(Closure))\n#82 \/core\/Console.php(85): Piwik\\Console->doRunImpl(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#83 \/vendor\/symfony\/console\/Application.php(171): Piwik\\Console->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#84 \/console(32): Symfony\\Component\\Console\\Application->run()\n#85 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(196): Piwik\\FrontController::(Object(TypeError))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 \/core\/CliMulti\/RequestCommand.php(75): require_once('\/i...')\n#9 \/core\/Plugin\/ConsoleCommand.php(110): Piwik\\CliMulti\\RequestCommand->doExecute()\n#10 \/vendor\/symfony\/console\/Command\/Command.php(298): Piwik\\Plugin\\ConsoleCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/core\/Plugin\/ConsoleCommand.php(125): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 \/vendor\/symfony\/console\/Application.php(1040): Piwik\\Plugin\\ConsoleCommand->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 \/vendor\/symfony\/console\/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand(Object(Piwik\\CliMulti\\RequestCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 \/core\/Console.php(106): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 [internal function]: Piwik\\Console->originDoRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 \/core\/Console.php(145): call_user_func(Array, Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 \/core\/Access.php(670): Piwik\\Console->Piwik\\{closure}()\n#18 \/core\/Console.php(146): Piwik\\Access::doAsSuperUser(Object(Closure))\n#19 \/core\/Console.php(85): Piwik\\Console->doRunImpl(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 \/vendor\/symfony\/console\/Application.php(171): Piwik\\Console->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 \/console(32): Symfony\\Component\\Console\\Application->run()\n#22 {main}"}

> Executed on CLI

**Comment by tsteur** [comment]
Test comment for sync

**Comment by tsteur** [comment]
I'll recreate that one as it doesn't seem to get synced. Maybe because it was closed earlier or has certain characters
