### ISSUE TITLE
[Bug]: Fatal error: Cannot access offset of type string on string in SitesManager/API.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21448]
### What happened?

This fatal error happened on 4.15.2-b1

> Error: {"message":"Cannot access offset of type string on string","file":"\/plugins\/SitesManager\/API.php","line":766,"request_id":"c53e5","backtrace":" on \/plugins\/SitesManager\/API.php(766)\n#0 \/plugins\/SitesManager\/API.php(1371): Piwik\\Plugins\\SitesManager\\API->setSettingValue('urls', NULL, Array, Array)\n#1 [internal function]: Piwik\\Plugins\\SitesManager\\API->updateSite('11', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Array, NULL, NULL)\n#2 \/core\/API\/Proxy.php(244): call_user_func_array(Array, Array)\n#3 \/core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#4 \/core\/API\/Proxy.php(335): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#5 \/core\/API\/Request.php(267): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'updateSite', Array)\n#6 \/plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#7 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#8 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#9 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#10 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#11 \/index.php(25): require_once('\/c...')\n#12 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(196): Piwik\\FrontController::(Object(TypeError))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

> URL: /?method=SitesManager.updateSite&idSite=11&parameters=undefined&module=API&format=json&settingValues%5BWebsiteMeasurable%5D%5B%5Bobject+Object%5D%5D%5Bvalue%5D=0

> Referrer:

### What should happen?

No error

### How can this be reproduced?

Unclear. See stack trace in "what happened"

### Matomo Version

Matomo 4

### Matomo Patch or Minor Version

15

### PHP Version

.

### Server Operating System

.

### Computer Operating System

.

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by bx80** [comment]
This looks like it might be caused by trying to set the urls for a measurable to null. There is a [related issue](https://github.com/matomo-org/matomo/issues/20057) which could potentially resolve this.
