### ISSUE TITLE
[Bug] Fatal error: Call to undefined method Piwik\\DataTable\\Map::getAllTableMetadata() in Actions/API.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21578]
### What happened?

This fatal error happened on 5.0.0-rc8

> Error: {"message":"Call to undefined method Piwik\\DataTable\\Map::getAllTableMetadata()","file":"\/plugins\/Actions\/API.php","line":453,"request_id":"d1c4a","backtrace":" on \/plugins\/Actions\/API.php(453)\n#0 \/plugins\/Actions\/API.php(491): Piwik\\Plugins\\Actions\\API->doFilterPageDatatableSearch(Array, Object(Piwik\\DataTable\\Map), Array)\n#1 \/plugins\/Actions\/API.php(439): Piwik\\Plugins\\Actions\\API->doFilterPageDatatableSearch(Array, Object(Piwik\\DataTable\\Map), Array)\n#2 \/plugins\/Actions\/API.php(420): Piwik\\Plugins\\Actions\\API->doFilterPageDatatableSearch(Array, Object(Piwik\\DataTable\\Map), Array)\n#3 \/plugins\/Actions\/API.php(207): Piwik\\Plugins\\Actions\\API->getFilterPageDatatableSearch(Array, 'https:\/\/www.exa...', 1)\n#4 [internal function]: Piwik\\Plugins\\Actions\\API->getPageUrl('https:\/\/www.exa...', 'all', 'day', 'last1000', false)\n#5 \/core\/API\/Proxy.php(255): call_user_func_array(Array, Array)\n#6 \/core\/Context.php(28): Piwik\\API\\Proxy->Piwik\\API\\{closure}()\n#7 \/core\/API\/Proxy.php(346): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#8 \/core\/API\/Request.php(272): Piwik\\API\\Proxy->call('\\\\Piwik\\\\Plugins\\\\...', 'getPageUrl', Array)\n#9 \/plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#10 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#11 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#12 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#13 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#14 \/index.php(25): require_once('\/c...')\n#15 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(196): Piwik\\FrontController::(Object(Error))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

> URL: /?module=API&method=Actions.getPageUrl&idSite=all&period=day&date=last1000&format=xml&token_auth=XYZANONYMIZED&pageUrl=https://www.example.com

> Referrer:

### What should happen?

No fatal error

### How can this be reproduced?

I assume the URL in the "what happened" section maybe allows reproducing it.

### Matomo major version

Matomo 5

### Matomo minor or patch Version

0

### PHP version

.

### Server operating system

.

### Computer operating system

.

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
This one should already exist in Matomo 4. The method simply doesn't fully support multiple table maps.
The requests generates one layer for idSites (as it's `all`) and one for the periods (as it's `last100`), but the maniuplation of the datatables only handles one layer of table maps. Refactoring the code to use datatable filters could solve the problem.
