### ISSUE TITLE
[Bug] Call to undefined method Map::getRows() in Flattener.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21740]
### What happened?

Below fatal error happened: 
This fatal error happened on 5.0.0-rc9.

> Error: {"message":"Call to undefined method Piwik\\DataTable\\Map::getRows()","file":"\/core\/API\/DataTableManipulator\/Flattener.php","line":201,"request_id":"653e7","backtrace":" on \/core\/API\/DataTableManipulator\/Flattener.php(201)\n#0 \/core\/API\/DataTableManipulator\/Flattener.php(93): Piwik\\API\\DataTableManipulator\\Flattener->flattenRow(Object(Piwik\\DataTable\\Row), 0, Object(Piwik\\DataTable), 1, 'MarketingCampai...', '', false)\n#1 \/core\/API\/DataTableManipulator\/Flattener.php(80): Piwik\\API\\DataTableManipulator\\Flattener->flattenDataTableInto(Object(Piwik\\DataTable), Object(Piwik\\DataTable), 1, 'MarketingCampai...')\n#2 \/core\/API\/DataTableManipulator.php(67): Piwik\\API\\DataTableManipulator\\Flattener->manipulateDataTable(Object(Piwik\\DataTable))\n#3 \/core\/API\/DataTableManipulator.php(83): Piwik\\API\\DataTableManipulator->manipulate(Object(Piwik\\DataTable))\n#4 \/core\/API\/DataTableManipulator.php(65): Piwik\\API\\DataTableManipulator->manipulateDataTableMap(Object(Piwik\\DataTable\\Map))\n#5 \/core\/API\/DataTableManipulator\/Flattener.php(52): Piwik\\API\\DataTableManipulator->manipulate(Object(Piwik\\DataTable\\Map))\n#6 \/core\/API\/DataTablePostProcessor.php(193): Piwik\\API\\DataTableManipulator\\Flattener->flatten(Object(Piwik\\DataTable\\Map), ' - ')\n#7 \/core\/API\/DataTablePostProcessor.php(116): Piwik\\API\\DataTablePostProcessor->applyFlattener(Object(Piwik\\DataTable\\Map))\n#8 \/core\/API\/ResponseBuilder.php(190): Piwik\\API\\DataTablePostProcessor->process(Object(Piwik\\DataTable\\Map))\n#9 \/core\/API\/ResponseBuilder.php(104): Piwik\\API\\ResponseBuilder->handleDataTable(Object(Piwik\\DataTable\\Map))\n#10 \/core\/API\/Request.php(278): Piwik\\API\\ResponseBuilder->getResponse(Object(Piwik\\DataTable\\Map), 'MarketingCampai...', 'getSourceMedium')\n#11 \/core\/Context.php(28): Piwik\\API\\Request->Piwik\\API\\{closure}()\n#12 \/core\/API\/Request.php(279): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure))\n#13 \/plugins\/API\/Controller.php(45): Piwik\\API\\Request->process()\n#14 [internal function]: Piwik\\Plugins\\API\\Controller->index()\n#15 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#16 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('API', false, Array)\n#17 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#18 \/index.php(25): require_once('\/c...')\n#19 {main}","safemode_backtrace":"#0 [internal function]: Piwik\\Plugins\\Cloud\\Controller->safemode(Array)\n#1 \/core\/FrontController.php(637): call_user_func_array(Array, Array)\n#2 \/core\/FrontController.php(169): Piwik\\FrontController->doDispatch('Cloud', 'safemode', Array)\n#3 \/core\/FrontController.php(100): Piwik\\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)\n#4 \/core\/FrontController.php(140): Piwik\\FrontController::(Array)\n#5 \/core\/FrontController.php(196): Piwik\\FrontController::(Object(Error))\n#6 \/core\/dispatch.php(32): Piwik\\FrontController->dispatch()\n#7 \/index.php(25): require_once('\/c...')\n#8 {main}"}

### What should happen?

No fatal error

### How can this be reproduced?

> URL: /?module=API&method=MarketingCampaignsReporting.getSourceMedium&idSite=3,4,5,6,7,8,2&period=range&date=2023-11-30,2023-12-27&expanded=0&flat=1&segment=&format=JSON&format_metrics=0&filter_limit=-1&filter_pattern_recursive=

### Matomo version

5

### PHP version

.

### Server operating system

.

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
This I guess never worked. The requests tries to fetch a flattened report for multiple idSites. This is something the flattener simply can't handle. This is something we need to implement or throw a proper expception instead if we don't want to support it.
Imho the expected behaviour would be to get the reports for all idSites flattened each.
