### ISSUE TITLE
[Bug]  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_time' in 'field list' - in plugin Funnels.

### ISSUE THREAD

**Issue by DmitrySadovnikov** [piwik/piwik#21822]
### What happened?

After update matomo from the v4 to v5 the command `./console core:archive` stopped working with the error: `Column not found: 1054 Unknown column 'created_time' in 'field list' - in plugin Funnels.`

### What should happen?

Archiving must be completed

### How can this be reproduced?

Download and install the `Funnels` plugin 
```
curl -o Funnels.zip -f -sS --data "access_token=YOUR_TOKEN_HERE " https://plugins.matomo.org/api/2.0/plugins/Funnels/download/latest?matomo=5.0.1 \
        && unzip Funnels.zip -d ./pluginsToActivate \
        && rm -f Funnels.zip

./console plugin:activate Funnels

./console core:update --yes
```

Run archiver
```
./console core:archive --concurrent-archivers 1
```

### Matomo version

5.0.1

### PHP version

8.2.14

### Server operating system

Debian GNU/Linux 12 (bookworm)

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Computer operating system

Debian GNU/Linux 12 (bookworm)

### Relevant log output

```shell
INFO [22:02:01] 1 Error: Got invalid response from API request: ?module=API&method=CoreAdminHome.archiveReports&idSite=1&period=day&date=2024-01-18&format=json&trigger=archivephp. Response was '{"result":"error","message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_time' in 'field list' - in plugin Funnels. #0 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(309): Piwik\\ArchiveProcessor\\PluginsArchiver-&gt;callAggregateAllPlugins(62, '21', false) #1 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(185): Piwik\\ArchiveProcessor\\Loader-&gt;prepareAllPluginsArchive(62, '21') #2 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(164): Piwik\\ArchiveProcessor\\Loader-&gt;insertArchiveData(57.0, 21.0, false, NULL) #3 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(104): Piwik\\ArchiveProcessor\\Loader-&gt;prepareArchiveImpl(false) #4 \/var\/www\/html\/core\/Context.php(75): Piwik\\ArchiveProcessor\\Loader-&gt;Piwik\\ArchiveProcessor\\{closure}() #5 \/var\/www\/html\/core\/ArchiveProcessor\/Loader.php(101): Piwik\\Context::changeIdSite(1, Object(Closure)) #6 \/var\/www\/html\/plugins\/CoreAdminHome\/API.php(297): Piwik\\ArchiveProcessor\\Loader-&gt;prepareArchive(false) #7 [internal function]: Piwik\\Plugins\\CoreAdminHome\\API-&gt;archiveReports('1', Object(Piwik\\Period\\Day), '2024-01-18', false, false, false) #8 \/var\/www\/html\/core\/API\/Proxy.php(255): call_user_func_array(Array, Array) #9 \/var\/www\/html\/core\/Context.php(28): Piwik\\API\\Proxy-&gt;Piwik\\API\\{closure}() #10 \/var\/www\/html\/core\/API\/Proxy.php(158): Piwik\\Context::executeWithQueryParameters(Array, Object(Closure)) #11 \/var\/www\/html\/core\/API\/Request.php(272): Piwik\\API\\Proxy-&gt;call('\\\\Piwik\\\\Plugins\\\\...', 'archiveReports', Array) #12 \/var\/www\/html\/plugins\/API\/Controller.php(45): Piwik\\API\\Request-&gt;process() #13 [internal function]: Piwik\\Plugins\\API\\Controller-&gt;index() #14 \/var\/www\/html\/core\/FrontController.php(637): call_user_func_array(Array, Array) #15 \/var\/www\/html\/core\/FrontController.php(169): Piwik\\FrontController-&gt;doDispatch('API', false, Array) #16 \/var\/www\/html\/core\/dispatch.php(32): Piwik\\FrontController-&gt;dispatch() #17 \/var\/www\/html\/index.php(25): require_once('\/var\/www\/html\/c...') #18 \/var\/www\/html\/core\/CliMulti\/RequestCommand.php(75): require_once('\/var\/www\/html\/i...') #19 \/var\/www\/html\/core\/Plugin\/ConsoleCommand.php(110): Piwik\\CliMulti\\RequestCommand-&gt;doExecute() #20 \/var\/www\/html\/vendor\/symfony\/console\/Command\/Command.php(298): Piwik\\Plugin\\ConsoleCommand-&gt;execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #21 \/var\/www\/html\/core\/Plugin\/ConsoleCommand.php(125): Symfony\\Component\\Console\\Command\\Command-&gt;run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #22 \/var\/www\/html\/vendor\/symfony\/console\/Application.php(1040): Piwik\\Plugin\\ConsoleCommand-&gt;run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #23 \/var\/www\/html\/vendor\/symfony\/console\/Application.php(301): Symfony\\Component\\Console\\Application-&gt;doRunCommand(Object(Piwik\\CliMulti\\RequestCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #24 \/var\/www\/html\/core\/Console.php(106): Symfony\\Component\\Console\\Application-&gt;doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #25 [internal function]: Piwik\\Console-&gt;originDoRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #26 \/var\/www\/html\/core\/Console.php(145): call_user_func(Array, Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #27 \/var\/www\/html\/core\/Access.php(670): Piwik\\Console-&gt;Piwik\\{closure}() #28 \/var\/www\/html\/core\/Console.php(143): Piwik\\Access::doAsSuperUser(Object(Closure)) #29 \/var\/www\/html\/core\/Console.php(85): Piwik\\Console-&gt;doRunImpl(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #30 \/var\/www\/html\/vendor\/symfony\/console\/Application.php(171): Piwik\\Console-&gt;doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #31 \/var\/www\/html\/console(32): Symfony\\Component\\Console\\Application-&gt;run() #32 {main}, caused by: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_time' in 'field list' #0 \/var\/www\/html\/libs\/Zend\/Db\/Statement.php(300): Zend_Db_Statement_Pdo-&gt;_execute(Array) #1 \/var\/www\/html\/libs\/Zend\/Db\/Adapter\/Abstract.php(479): Zend_Db_Statement-&gt;execute(Array) #2 \/var\/www\/html\/libs\/Zend\/Db\/Adapter\/Pdo\/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query('INSERT IGNORE I...', Array) #3 \/var\/www\/html\/core\/Db\/Adapter\/Pdo\/Mysql.php(332): Zend_Db_Adapter_Pdo_Abstract-&gt;query('INSERT IGNORE I...', Array) #4 \/var\/www\/html\/core\/Db.php(281): Piwik\\Db\\Adapter\\Pdo\\Mysql-&gt;query('INSERT IGNORE I...', Array) #5 \/var\/www\/html\/core\/Db\/BatchInsert.php(43): Piwik\\Db::query('INSERT IGNORE I...', Array) #6 \/var\/www\/html\/core\/Db\/BatchInsert.php(135): Piwik\\Db\\BatchInsert::tableInsertBatchIterate('dbuser_log_funn...', Array, Array) #7 \/var\/www\/html\/plugins\/Funnels\/Dao\/LogTable.php(191): Piwik\\Db\\BatchInsert::tableInsertBatch('dbuser_log_funn...', Array, Array, false, 'latin1') #8 \/var\/www\/html\/plugins\/Funnels\/Archiver\/Populator.php(290): Piwik\\Plugins\\Funnels\\Dao\\LogTable-&gt;bulkInsert(1, 3, 1, A ... )\n#46 \/var\/www\/html\/console(32): Symfony\\Component\\Console\\Application->run()\n#47 {main}"}'
```
```


### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by AltamashShaikh** [comment]
@DmitrySadovnikov Can you run this SQL command ? This was a new column added in Matomo 5 for performance improvement
```
ALTER TABLE `matomo_log_funnel` ADD `created_time` DATETIME NOT NULL
```

**Comment by DmitrySadovnikov** [comment]
> @DmitrySadovnikov Can you run this SQL command ? This was a new column added in Matomo 5 for performance improvement
> 
> ```
> ALTER TABLE `matomo_log_funnel` ADD `created_time` DATETIME NOT NULL
> ```

Thank you @AltamashShaikh. This has fixed the error.

**Comment by michalkleiner** [comment]
@DmitrySadovnikov just putting this info here for a good measure — as Funnels is a premium plugin, don't hesitate to contact the support team at shop@innocraft.com in future should you encounter an issue with it. This repository and the issue tracker is primarily for the core Matomo application, not for premium plugins. Thanks, we do appreciate your understanding!

**Comment by michalkleiner** [comment]
@AltamashShaikh just checking — is the migration (the column addition) covered in the plugin or do we need something more? Thanks!

**Comment by AltamashShaikh** [comment]
@michalkleiner Its covered in migration script in the plugin.
![Screenshot from 2024-01-19 06-41-08](https://github.com/matomo-org/matomo/assets/14902277/d1c55755-1e29-42ee-b4fd-3d4bdde6328b)
