### ISSUE TITLE
[Bug] matomo.js erroring on javaEnabled property

### ISSUE THREAD

**Issue by terminatingcode** [piwik/piwik#22836]
### What happened?

Errors started coming through on our end since Dec 9, 10:02 PM

Our Matomo.js script is erroring on accessing the  `javaEnabled` property

Looking at the stats, all users initiating the error are on Chrome browser (`125.0.6422`, `126.0.6478`, `127.0.6523`) and Windows >10.

### What should happen?

no error

### How can this be reproduced?

n/a

### Matomo version

matomo.js

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
'get' on proxy: property 'javaEnabled' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'function () {
            return false;
        }' but got 'function (...args) {
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by fattybenji** [comment]
Same problem here, also started appearing on december 9th around 10pm (CET)

A little bit more output:

```
'get' on proxy: property 'javaEnabled' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'function () {
            return false;
        }' but got 'function (...args) {
                return value.apply(target, args);
            }')
```

We're using version 5.1.1.

Update: we've noticed that all calls come from Microsoft IPs.

**Comment by Yhuley** [comment]
We have same problem.

All users who initiate the error use Chrome (125.0.6422, 127.0.6523) and Windows >10

**Comment by sgiehl** [comment]
I've tried to check that using browser stack, but can't see any error when visiting a page where the matomo tracker is integrated with older chrome versions on windows 10 or windows 11.
Is anyone of you maybe able to share a link to a site where that error occurs?

**Comment by david-bezero** [comment]
@sgiehl does the matomo code create a proxy around the `navigator` object at all?

If so, it seems this bug is caused by that proxy, which will need fixing here.

If not, it seems likely (from @fattybenji noting that this is limited to Microsoft IPs) that this is coming from (e.g.) a malware scanning service which is creating its own `navigator` proxy object, with the issue being _triggered_ by matomo only because it attempts to access a property that they haven't set up correctly. Unfortunately Microsoft [has form here](https://github.com/getsentry/sentry-javascript/issues/3440) and the common advice is to simply filter out the errors since they won't fix them.

In the latter case, one option matomo might want to consider is to simply not invoke (or even access) `javaEnabled` unless the browser is detected to be one where this might return a meaningful value (since it is deprecated and all modern browsers hard-code it to `false` anyway).

**Comment by david-bezero** [comment]
on your question about the call site, it is reported as `matomo.js in c6 at line 40:841`, which appears to be here in the unminified code: https://github.com/matomo-org/matomo/blob/20cfe2d3a6afcd211fd50545f5b387da0b99736c/js/piwik.js#L3422

(specifically on the `typeof navigator.javaEnabled` check)

**Comment by sgiehl** [comment]
We are unable to reproduce that. Is anyone able to reproduce that manually or can anyone provide an URL where that happened?
Without a proper reproduction it's hard to say where the problem is and how to fix this. 
It could in theory even be an automated crawler doing weird things 🤷

**Comment by david-bezero** [comment]
> It could in theory even be an automated crawler doing weird things

I think this is the most likely explanation (see my first comment for details)

I'm not aware of this happening in a browser I have access to; just getting reports from the automated error handling.

The root cause is probably for Microsoft to fix, but I doubt they'll look at it. It would be _nice_ if matomo updated this code to only check `javaEnabled` for browsers where it might be meaningful (which would fix this as a side-effect), especially since I imagine 99.9% of Matomo's users don't even care about the presence of Java on client machines!

The only other option is for every matomo user to add this to their list of ignored errors, to avoid noise from Microsoft's scans.

**Comment by sgiehl** [comment]
We could also add a try/catch around that block. But it's hard to test if that works as expected.
Only checking the flag based on the detected browser might also not work reliable if someone spoofs a different browser

**Comment by david-bezero** [comment]
FWIW there's already a browser check for Edge on that code, which would have a similar limitation with spoofing.

You can replicate the issue with this setup code, which may or may not be entirely representative of what Microsoft's environment is using:

```js
Object.defineProperty(navigator, 'javaEnabled', {
  value: () => false,
  writeable: false,
  configurable: false,
});

Object.defineProperty(window, 'navigator', {
  value: new Proxy(window.navigator, {
    get(target, prop, receiver) {
      if (prop === 'javaEnabled') return () => false;
      return Reflect.get(target, prop, receiver);
    }
  }),
});

// now accessing navigator.javaEnabled throws the error from this thread
```

**Comment by ipecador** [comment]
If I correctly understand the code, the problematic code is within a block that excludes IE < 11 but does not call `navigatorAlias` because it does not exist under IE6/IE7. This (now) looks like useless code.

https://github.com/matomo-org/matomo/blob/20cfe2d3a6afcd211fd50545f5b387da0b99736c/js/piwik.js#L3407
https://github.com/matomo-org/matomo/blob/20cfe2d3a6afcd211fd50545f5b387da0b99736c/js/piwik.js#L3419

It seems to me that the problematic line has no more reason to be there so deleting it may (slightly) lighten the code and fix this issue.

https://github.com/matomo-org/matomo/blob/20cfe2d3a6afcd211fd50545f5b387da0b99736c/js/piwik.js#L3422

**Comment by petergoes** [comment]
@sgiehl 
I see this issue in pop up in our Sentry error tracking all the time.

One of the urls Sentry is reporting:
https://decorrespondent.nl/15760/de-slechtste-baas-is-de-baas-die-de-baas-wil-worden-en-meer-wetenschappelijke-inzichten-over-de-baas/c9a91565-2d3f-0e2b-085c-2187ea063d12

Other data from Sentry:

![image](https://github.com/user-attachments/assets/afd59c11-0355-4d78-ba1c-4d050c24cd25)

Hope this helps you

**Comment by sgiehl** [comment]
@petergoes I've tried your URL with all those Chrome versions using BrowserStack and none of them is throwing that JavaScript error for me. Are you maybe also able to see if all the traffic is coming from the same IP (range)?

**Comment by petergoes** [comment]
@sgiehl, I accumulated the multiple sentry issues regarding this issue and I can definitely say that there are multiple users (with different ip addresses) that experience this issue

see this screenshot, which tells me that we have 1.3K users experiencing this issue
![image](https://github.com/user-attachments/assets/ea259ddd-30eb-4a7f-940f-05f652f91144)

**Comment by GitHubIsShortOnUsernames** [comment]
Looking at a handful of those errors, they indeed come from MS IPs, likely Azure or one of their own crawlers. The comparatively low frequency suggests it's not related to any current mainstream browser. It's still a bit annoying for those who log client side errors.

**Comment by neubreed** [comment]
Hello,

I am also getting a lot of these errors in my client-side error logging. Looks like the IP is also from Microsoft.

``
[2025-01-20 09:59:21] ERROR: Uncaught TypeError: 'get' on proxy: property 'javaEnabled' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'function () {             return false;         }' but got 'function (...args) {                 return value.apply(target, args);             }') [500,"Lovefest Natural Bridge",null] {"url":"/app/log-error","ip":"40.94.95.96","http_method":"POST","server":"undiscovered.events","referrer":"https://undiscovered.events/lovefestnaturalbridge"}
``

```
{
    "type": "General Error",
    "source": "/matomo.js",
    "line": 40,
    "column": 841,
    "error": "TypeError: 'get' on proxy: property 'javaEnabled' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'function () {\r\n            return false;\r\n        }' but got 'function (...args) {\r\n                return value.apply(target, args);\r\n            }')",
    "exception": "TypeError: 'get' on proxy: property 'javaEnabled' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'function () {\r
            return false;\r
        }' but got 'function (...args) {\r
                return value.apply(target, args);\r
            }')
    at c6 (https://matomo.neubreed.com/matomo.js:40:841)
    at df (https://matomo.neubreed.com/matomo.js:41:285)
    at dc (https://matomo.neubreed.com/matomo.js:42:293)
    at a9 (https://matomo.neubreed.com/matomo.js:42:345)
    at aV (https://matomo.neubreed.com/matomo.js:42:636)
    at unload (https://matomo.neubreed.com/matomo.js:68:659)
    at ah (https://matomo.neubreed.com/matomo.js:14:293)
    at an (https://matomo.neubreed.com/matomo.js:14:364)",
    "url": "/lovefestnaturalbridge",
    "user": null
}
```

[https://search.dnslytics.com/ip/40.94.95.96
](https://search.dnslytics.com/ip/40.94.95.96)

**Comment by tortuch** [comment]
Hi, I have the same error on my also, Did you sovle this error?

**Comment by timmyrosen** [comment]
Is there any update on this? This issue is causing trouble for our users

**Comment by sarapov2003v** [comment]
Is there any update on this?

**Comment by sarapov2003v** [comment]
@nac62116 I'm not sure if this is related with the issue you created.
https://github.com/mint-vernetzt/community-platform/issues/1846

**Comment by Smagia** [comment]
I've a similar error, and this happens quite often.
Also for us the problem appears on Windows 10 machine with Chrome `127.0.6523`

**Comment by sarapov2003v** [comment]
I have still same error, is there any updates?

**Comment by viclarsson** [comment]
Experiencing this error as well but haven't been able to reproduce. How is it affecting your users @timmyrosen?

**Comment by daoyuly** [comment]
I've a similar error, and this happens quite often.

`TypeError: 'get' on proxy: property 'javaEnabled' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'function () {
            return false;
        }' but got 'function (...args) {`

**Comment by mav10** [comment]
+1
