### ISSUE TITLE
[Bug] mb_strtolower(): Argument #1 ($string) must be of type string, array given in Referrers/Columns/Base.php:58

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#22847]
### What happened?

This is on PHP 8.2

Happens few times per day.

Backtrace:

> PHP Fatal error: Uncaught TypeError: mb_strtolower(): Argument #1 ($string) must be of type string, array given in /var/www/html/plugins/Referrers/Columns/Base.php:589 Stack trace: #0 /var/www/html/plugins/Referrers/Columns/Base.php(589): mb_strtolower() #1 /var/www/html/plugins/Referrers/Columns/Base.php(123): Piwik\Plugins\Referrers\Columns\Base->detectReferrerCampaign() #2 /var/www/html/plugins/Referrers/Columns/Base.php(269): Piwik\Plugins\Referrers\Columns\Base->getReferrerInformation() #3 /var/www/html/plugins/Referrers/Columns/Campaign.php(43): Piwik\Plugins\Referrers\Columns\Base->getReferrerInformationFromRequest() #4 /var/www/html/core/Tracker/Visit.php(545): Piwik\Plugins\Referrers\Columns\Campaign->shouldForceNewVisit() #5 /var/www/html/core/Tracker/Visit.php(173): Piwik\Tracker\Visit->triggerPredicateHookOnDimensions() #6 /var/www/html/core/Tracker.php(171): Piwik\Tracker\Visit->handle() #7 /var/www/html/core/Tracker/Handler.php(55): Piwik\Tracker->trackRequest() #8 /var/www/html/core/Tracker.php(151): Piwik\Tracker\Handler->process() #9 /var/www/html/core/Tracker.php(126): Piwik\Tracker->track() #10 /var/www/html/piwik.php(73): Piwik\Tracker->main() #11 {main} thrown in /var/www/html/plugins/Referrers/Columns/Base.php on line 589

### What should happen?

No fatal error

### How can this be reproduced?

.

### Matomo version

5

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
@tsteur Are we by any chance able to look up the tracking url causing this error? It seems like for any reason the referrer name is set to an array instead of a string. But it's hard to determine where that comes from.
