### ISSUE TITLE
import_logs.py fails when "php" is not available (OSError: [Errno 2] No such file or directory)

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik#4835]
Since 5 days, my piwik import_logs.py do nothing.
See the following error.

```
root@s15879177:~# python /var/www/tools/piwik/misc/log-analytics/import_logs.py --url=https://mywebsite/piwik/ --idsite=1 --show-progress --recorders=4 --enable-reverse-dns --useragent-exclude=oui-moi-cmoi --exclude-path=/robots.txt --exclude-path=/ubuntu/* --exclude-path=/public/ubuntu/* --exclude-path=*.svg.php /var/log/lighttpd/access.log.6.gz
Traceback (most recent call last):
  File "/var/www/tools/piwik/misc/log-analytics/import_logs.py", line 1722, in <module>
    config = Configuration()
  File "/var/www/tools/piwik/misc/log-analytics/import_logs.py", line 570, in __init__
    self._parse_args(self._create_parser())
  File "/var/www/tools/piwik/misc/log-analytics/import_logs.py", line 560, in _parse_args
    self.options.piwik_token_auth = self._get_token_auth()
  File "/var/www/tools/piwik/misc/log-analytics/import_logs.py", line 607, in _get_token_auth
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
