### ISSUE TITLE
Log analytics: import_logs.py returns Error: Not Found

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#5059]
When I run the script to ingest log files it fails with the following errors:

root@demo:/var/www/piwik/logs# python /var/www/piwik/misc/log-analytics/import_logs.py --url=http://129.123.194.52/piwik --idsite 2 --enable-static --enable-bots ./intra.log
Traceback (most recent call last):
File "/var/www/piwik/misc/log-analytics/import_logs.py", line 1760, in
resolver = config.get_resolver()
File "/var/www/piwik/misc/log-analytics/import_logs.py", line 660, in get_resolver
return StaticResolver(self.options.site_id)
File "/var/www/piwik/misc/log-analytics/import_logs.py", line 1005, in __init__
'SitesManager.getSiteFromId', idSite=self.site_id
File "/var/www/piwik/misc/log-analytics/import_logs.py", line 987, in call_api
return cls._call_wrapper(cls._call_api, None, None, method, **kwargs)
File "/var/www/piwik/misc/log-analytics/import_logs.py", line 976, in _call_wrapper
raise Piwik.Error(message)
__main__.Error: Not Found

What do I do to fix this?

**Comment by mattab** [comment]
Issue was moved to the new repository for Piwik Log Analytics: https://github.com/piwik/piwik-log-analytics/issues

refs #7163
