### ISSUE TITLE
Error in widgets when date range before website added.

### ISSUE THREAD

**Issue by strayobject** [piwik/piwik#6811]
Suppose there are two websites (A & B) tracked and today is 05.01.2014. Website A was added on 01.01.2014 and B on 05.01.2014 (imaginary today). When we go to website A's Dashboard and select date range from 01.01 to 04.01 and then select website B from the website dropdown we are presented with the following error on most widgets. 

**(This is replicable on demo site, read at the bottom)**

```
ERROR CoreHome[2014-12-04 21:45:46] [1ea72] Failed to get data from API: Specified date range is invalid.#0 [...]/core/Period.php(272): Piwik\Period\Range->getDateStart()#1 [...]/core
/Archive/DataCollection.php(120): Piwik\Period->getRangeString()#2 [...]/core/Archive.php(506): Piwik\Archive\DataCollection->__construct(Array, 'blob', Array, Array, NULL)#3 [...]/core/Archive.php(375): Piwik\Archive->get('Referrers_searc...', 'blob', NULL)#4 [...]/core/Archive.php(470): Piwik\Archive->getDataTable('Referrers_searc...', NULL)#5 [...]/plugins/Referrers/API.php(45): Piwik\Archive::getDataTableFromArchive('Referrers_searc...', '6', 'range', '2014-12-04,2014...', false, false, NULL)#6 [...]/plugins/Referrers/API.php(138): Piwik\Plugins\Referrers\API->getDataTable('Referrers_searc...', '6', 'range', '2014-12-04,2014...', false, false)#7 [internal function]: Piwik\Plugins\Referrers\API->getKeywords('6', 'range', '2014-12-04,2014...', false, false)#8 [...]/core/API/Proxy.php(211): call_user_func_array(Array, Array)#9 [...]/core/API/Request.php(216): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'getKeywords', Array)#10 [...]/core/ViewDataTable/Request.php(48): Piwik\API\Request->process()#11 [...]/core/Plugin/ViewDataTable.php(327): Piwik\ViewDataTable\Request->loadDataTableFromAPI(Array)#12 [...]/core/Plugin/Visualization.php(166): Piwik\Plugin\ViewDataTable->loadDataTableFromAPI(Array)#13 [...]/core/Plugin/ViewDataTable.php(414): Piwik\Plugin\Visualization->buildView()#14 [...]/core/Plugin/Report.php(304): Piwik\Plugin\ViewDataTable->render()#15 [...]/plugins/CoreHome/Controller.php(78): Piwik\Plugin\Report->render()#16 [internal function]: Piwik\Plugins\CoreHome\Controller->renderReportWidget('Referrers', 'getKeywords')#17 [...]/core/FrontController.php(582): call_user_func_array(Array, Array)#18 [...]/core/FrontController.php(96): Piwik\FrontController->doDispatch(NULL, NULL, NULL)#19 [...]/core/dispatch.php(36): Piwik\FrontController->dispatch()#20 [...]/index.php(46): require_once('[...]')#21 {main}

Specified date range is invalid.
```

To replicate this issue on demo, select virtual-drums from dropdown. In the date range enter (from) 2008-01-26 (to) 2008-07-01 click 'apply date range' and switch to crowdfunding website.

**Comment by mattab** [comment]
The bug occurs when the "Website creation date" is newer than the date range. We should be smart here for example the code could assume the date start, was the earliest accepted date, rather than fail.

**Comment by mattab** [comment]
Thanks for the report!
