### ISSUE TITLE
You are logged in as 'admin' but it seems you don't have any permission set in Piwik

### ISSUE THREAD

**Issue by heidarymr** [piwik/piwik#7203]
I had an old piwik server (version 1.12)
I install Piwik 2.10 in new server then backup database with:
```$ mysqldump --opt -u [uname] -p[pass] [dbname] > [backupfile.sql]```
and restore with:
```$ mysql -u [uname] -p[pass] [db_to_restore] < [backupfile.sql]```
note:before restore i delete all tables.
then update piwik by command line
but now when i want to login to piwik i get this error
```
You are logged in as 'admin' but it seems you don't have any permission set in Piwik. 
Ask your Piwik administrator (click to email) to give you 'view' access to a website.
```

**Comment by heidarymr** [comment]
here you can download .sql database structure:
http://we.tl/XKjKZCnX4y

**Comment by heidarymr** [comment]
i remove  config.ini.php and reinstall piwik and my problem solved
but now i have new error:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_visit.config_device_type' in 'field list'
```

and:
```
WARNING DevicesDetection[2015-02-14 07:44:52] [efba6] /var/www/vhosts/piwik.xx/httpdocs/plugins/DevicesDetection/Visitor.php(24): Notice - Undefined index: config_device_type - Piwik 2.10.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
```

and:
```
ERROR VisitsSummary[2015-02-14 07:44:25] [ace25] Failed to get data from API: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_visit.config_device_type' in 'field list' #0 /var/www/vhosts/piwik.xx/httpdocs/libs/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo-&gt;_execute(Array) #1 /var/www/vhosts/piwik.xx/httpdocs/libs/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement-&gt;execute(Array) #2 /var/www/vhosts/piwik.xx/httpdocs/libs/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query('????SELECT?????...', Array) #3 /var/www/vhosts/piwik.xx/httpdocs/core/Db/Adapter/Pdo/Mysql.php(234): Zend_Db_Adapter_Pdo_Abstract-&gt;query('????SELECT?????...', Array) #4 /var/www/vhosts/piwik.xx/httpdocs/core/DataAccess/LogAggregator.php(323): Piwik\Db\Adapter\Pdo\Mysql-&gt;query('????SELECT?????...', Array) #5 /var/www/vhosts/piwik.xx/httpdocs/core/DataAccess/LogAggregator.php(227): Piwik\DataAccess\LogAggregator-&gt;queryVisitsByDimension(Array) #6 /var/www/vhosts/piwik.xx/httpdocs/plugins/DevicesDetection/Archiver.php(66): Piwik\DataAccess\LogAggregator-&gt;getMetricsFromVisitByDimension('config_device_t...') #7 /var/www/vhosts/piwik.xx/httpdocs/plugins/DevicesDetection/Archiver.php(36): Piwik\Plugins\DevicesDetection\Archiver-&gt;aggregateByLabel('config_device_t...', 'DevicesDetectio...') #8 /var/www/vhosts/piwik.xx/httpdocs/core/ArchiveProcessor/PluginsArchiver.php(109): Piwik\Plugins\DevicesDetection\Archiver-&gt;aggregateDayReport() #9 /var/www/vhosts/piwik.xx/httpdocs/core/ArchiveProcessor/Loader.php(122): Piwik\ArchiveProcessor\PluginsArchiver-&gt;callAggregateAllPlugins('2706', '1099') #10 /var/www/vhosts/piwik.xx/httpdocs/core/ArchiveProcessor/Loader.php(72): Piwik\ArchiveProcessor\Loader-&gt;prepareAllPluginsArchive(false, false) #11 /var/www/vhosts/piwik.xx/httpdocs/core/Archive.php(875): Piwik\ArchiveProcessor\Loader-&gt;prepareArchive('VisitsSummary') #12 /var/www/vhosts/piwik.xx/httpdocs/core/Archive.php(685): Piwik\Archive-&gt;prepareArchive(Array, Object(Piwik\Site), Object(Piwik\Period\Day)) #13 /var/www/vhosts/piwik.xx/httpdocs/core/Archive.php(639): Piwik\Archive-&gt;cacheArchiveIdsAfterLaunching(Array, Array) #14 /var/www/vhosts/piwik.xx/httpdocs/core/Archive.php(579): Piwik\Archive-&gt;getArchiveIds(Array) #15 /var/www/vhosts/piwik.xx/httpdocs/core/Archive.php(354): Piwik\Archive-&gt;get(Array, 'numeric') #16 /var/www/vhosts/piwik.xx/httpdocs/plugins/VisitsSummary/API.php(35): Piwik\Archive-&gt;getDataTableFromNumeric(Array) #17 [internal function]: Piwik\Plugins\VisitsSummary\API-&gt;get('2', 'day', '2015-01-16,2015...', false, 'nb_visits') #18 /var/www/vhosts/piwik.xx/httpdocs/core/API/Proxy.php(211): call_user_func_array(Array, Array) #19 /var/www/vhosts/piwik.xx/httpdocs/plugins/API/API.php(404): Piwik\API\Proxy-&gt;call('\Piwik\Plugins\...', 'get', Array) #20 [internal function]: Piwik\Plugins\API\API-&gt;get('2', 'day', '2015-01-16,2015...', false, 'nb_visits') #21 /var/www/vhosts/piwik.xx/httpdocs/core/API/Proxy.php(211): call_user_func_array(Array, Array) #22 /var/www/vhosts/piwik.xx/httpdocs/core/API/Request.php(231): Piwik\API\Proxy-&gt;call('\Piwik\Plugins\...', 'get', Array) #23 /var/www/vhosts/piwik.xx/httpdocs/core/ViewDataTable/Request.php(48): Piwik\API\Request-&gt;process() #24 /var/www/vhosts/piwik.xx/httpdocs/core/Plugin/ViewDataTable.php(327): Piwik\ViewDataTable\Request-&gt;loadDataTableFromAPI(Array) #25 /var/www/vhosts/piwik.xx/httpdocs/core/Plugin/Visualization.php(176): Piwik\Plugin\ViewDataTable-&gt;loadDataTableFromAPI(Array) #26 /var/www/vhosts/piwik.xx/httpdocs/core/Plugin/ViewDataTable.php(414): Piwik\Plugin\Visualization-&gt;buildView() #27 /var/www/vhosts/piwik.xx/httpdocs/core/Plugin/Controller.php(249): Piwik\Plugin\ViewDataTable-&gt;render() #28 /var/www/vhosts/piwik.xx/httpdocs/plugins/VisitsSummary/Controller.php(104): Piwik\Plugin\Controller-&gt;renderView(Object(Piwik\Plugins\CoreVisualizations\Visualizations\JqplotGraph\Evolution)) #29 [internal function]: Piwik\Plugins\VisitsSummary\Controller-&gt;getEvolutionGraph() #30 /var/www/vhosts/piwik.xx/httpdocs/core/FrontController.php(586): call_user_func_array(Array, Array) #31 /var/www/vhosts/piwik.xx/httpdocs/core/FrontController.php(96): Piwik\FrontController-&gt;doDispatch(NULL, NULL, NULL) #32 /var/www/vhosts/piwik.xx/httpdocs/core/dispatch.php(31): Piwik\FrontController-&gt;dispatch() #33 /var/www/vhosts/piwik.xx/httpdocs/index.php(27): require_once('/var/www/vhosts...') #34 {main}

```

**Comment by tsteur** [comment]
Have a look here, it might help: https://github.com/piwik/piwik/issues/7194#issuecomment-74316484
