### ISSUE TITLE
2.13.0-b3 error

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/piwik#7730]
```php
[21-Apr-2015 10:55:30 UTC] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'ContainerBuilder::addDefinitions() parameter must be a string or implement ChainableDefinitionSource, Piwik\Container\IniConfigDefinitionSource given' in D:\htdocs\piwik\vendor\mnapoli\php-di\src\DI\ContainerBuilder.php:261
Stack trace:
#0 D:\htdocs\piwik\core\Container\ContainerFactory.php(57): DI\ContainerBuilder->addDefinitions(Object(Piwik\Container\IniConfigDefinitionSource))
#1 D:\htdocs\piwik\core\Container\StaticContainer.php(74): Piwik\Container\ContainerFactory->create()
#2 D:\htdocs\piwik\core\Container\StaticContainer.php(47): Piwik\Container\StaticContainer::createContainer()
#3 D:\htdocs\piwik\core\Container\StaticContainer.php(101): Piwik\Container\StaticContainer::getContainer()
#4 D:\htdocs\piwik\core\Cache.php(56): Piwik\Container\StaticContainer::get('Piwik\\Cache\\Eag...')
#5 D:\htdocs\piwik\core\Plugin\Manager.php(123): Piwik\Cache::getEagerCache()
#6 D:\htdocs\piwik\core\Tracker.php(66): Piwik\Plugin\Manager->loadTrackerPlugins( in D:\htdocs\piwik\vendor\mnapoli\php-di\src\DI\ContainerBuilder.php on line 261
```

**Comment by ThaDafinser** [comment]
composer install :+1:

**Comment by thomaszbz** [comment]
I get this error after update from 2.12.0 to 2.13.0 (stable), using php 5.6.7 (debian 8 stable).

I have piwik installed via git, and I also performed a

    git submodule update
