### ISSUE TITLE
button click event tag json error

### ISSUE THREAD

**Issue by bangdon2** [piwik/piwik#8412]
<a href="#" onclick="javascript:_paq.push(['trackEvent', 'Menu', 'Freedom']);">Freedom page</a> 

I used that javascript 

but it is error 

at Object.stringify (native) 
at appendCustomVariablesToRequest (http://mng.logbox.co.kr/piwik.js:3108:60) 
at getRequest (http://mng.logbox.co.kr/piwik.js:3118:28) 
at logEvent (http://mng.logbox.co.kr/piwik.js:3773:31) 
at http://mng.logbox.co.kr/piwik.js:5312:25 
at trackCallback (http://mng.logbox.co.kr/piwik.js:3870:17) 
at Object.Piwik.trackEvent (http://mng.logbox.co.kr/piwik.js:5311:21) 
at Object.apply [as push] (http://mng.logbox.co.kr/piwik.js:580:37) 
at <anonymous>:2:6 
at Object.InjectedScript._evaluateOn (<anonymous>:895:140)appendCustomVariablesToRequest @ piwik.js:3108getRequest @ piwik.js:3118logEvent @ piwik.js:3773(anonymous function) @ piwik.js:5312trackCallback @ piwik.js:3870Piwik.trackEvent @ piwik.js:5311apply @ piwik.js:580(anonymous function) @ VM1375:2InjectedScript._evaluateOn @ VM1370:895InjectedScript._evaluateAndWrap @ VM1370:828InjectedScript.evaluate @ VM1370:694 

3108 lines 
3106 // Custom Variables, scope "page" 
3107 function appendCustomVariablesToRequest(customVariables, parameterName) { 
3108 var customVariablesStringified = JSON2.stringify(customVariables); 
3109 if (customVariablesStringified.length > 2) { 
3110 return '&' + parameterName + '=' + encodeWrapper(customVariablesStringified); 
3111 } 
3112 return ''; 
3113 }

**Comment by tsteur** [comment]
Can you add the Piwik code that you use to set custom variables? 

Do you maybe use prototype.js library (version 1.6.1 or so) by any chance on your website?

**Comment by bangdon2** [comment]
<a href="#" onclick="javascript:_paq.push(['trackEvent', 'Menu', 'Freedom']);">Freedom page</a> 

I used that javascript 

but it is error

**Comment by bangdon2** [comment]
my site mng.logbox.co.kr 

I not set custom variables

just set /a href="#" onclick="javascript:_paq.push(['trackEvent', 'Menu', 'Freedom']);">Freedom page</a/

**Comment by tsteur** [comment]
I tested this example link and it works for me. Can you send us a link where it is actually implemented so we can reproduce? Feel free to send us via email to hello @ piwik.org or post here.

**Comment by mattab** [comment]
Please re-open if you still have a problem
