### ISSUE TITLE
GeoIPAutoUpdater fails with "failed to unzip '/var/www/stat/misc/GeoIPCity.dat.dat.gz'

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9544]
`GeoIPAutoUpdater: failed to unzip '/var/www/stat/misc/GeoIPCity.dat.dat.gz' after downloading 'http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz': The downloaded file is not a valid GeoIP database. Please re-check the URL or download the file manually.`

As reported in http://forum.piwik.org/t/geoipautoupdater-error/16143

**Comment by mattab** [comment]
Notes
* This is reproducible on demo and demo2. I didn't notice but we did get email notification errors from the cron
* that there is twice `.dat` in the filename, which maybe indicates an error (or maybe not?) `failed to unzip '/var/www/stat/misc/GeoIPCity.dat.dat.gz`. 


Full error trace is:
```
ERROR [2016-01-06 00:56:32] /home/piwik-demo/www/demo.piwik.org/plugins/UserCountry/GeoIPAutoUpdater.php(161): GeoIPAutoUpdater: failed to unzip '/home/piwik-demo/www/demo.piwik.org/misc/GeoIPCity.dat.dat.gz' after downloading 'http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz': The downloaded file is not a valid GeoIP database. Please re-check the URL or download the file manually.
#0 /home/piwik-demo/www/demo.piwik.org/plugins/UserCountry/GeoIPAutoUpdater.php(96): Piwik\Plugins\UserCountry\GeoIPAutoUpdater->downloadFile('loc', 'http://geolite....')
#1 [internal function]: Piwik\Plugins\UserCountry\GeoIPAutoUpdater->update(NULL)
#2 /home/piwik-demo/www/demo.piwik.org/core/Scheduler/Scheduler.php(227): call_user_func(Array, NULL)
#3 /home/piwik-demo/www/demo.piwik.org/core/Scheduler/Scheduler.php(124): Piwik\Scheduler\Scheduler->executeTask(Object(Piwik\Plugins\UserCountry\GeoIPAutoUpdater))
#4 /home/piwik-demo/www/demo.piwik.org/plugins/CoreAdminHome/API.php(55): Piwik\Scheduler\Scheduler->run()
#5 /home/piwik-demo/www/demo.piwik.org/core/CronArchive.php(529): Piwik\Plugins\CoreAdminHome\API->runScheduledTasks()
#6 /home/piwik-demo/www/demo.piwik.org/core/CronArchive.php(283): Piwik\CronArchive->runScheduledTasks()
#7 /home/piwik-demo/www/demo.piwik.org/core/Access.php(466): Piwik\CronArchive->Piwik\{closure}()
#8 /home/piwik-demo/www/demo.piwik.org/core/CronArchive.php(285): Piwik\Access::doAsSuperUser(Object(Closure))
#9 /home/piwik-demo/www/demo.piwik.org/plugins/CoreConsole/Commands/CoreArchiver.php(27): Piwik\CronArchive->main()
#10 /home/piwik-demo/www/demo.piwik.org/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreConsole\Commands\CoreArchiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/piwik-demo/www/demo.piwik.org/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/piwik-demo/www/demo.piwik.org/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\CoreConsole\Commands\CoreArchiver), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/piwik-demo/www/demo.piwik.org/core/Console.php(79): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/piwik-demo/www/demo.piwik.org/core/Access.php(466): Piwik\Console->Piwik\{closure}()
#16 /home/piwik-demo/www/demo.piwik.org/core/Console.php(80): Piwik\Access::doAsSuperUser(Object(Closure))
#17 /home/piwik-demo/www/demo.piwik.org/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/piwik-demo/www/demo.piwik.org/misc/cron/archive.php(57): Symfony\Component\Console\Application->run()
#19 {main}
```

**Comment by mattab** [comment]
Adding to 2.16.0 - @tsteur @sgiehl maybe you could take a look at this one? It started occuring in November and seems to be experienced by all users.

**Comment by tsteur** [comment]
FYI: `geoip.loc_db_url` in option table in DB says `http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz` on demo. Had a quick look but code is almost impossible to understand so needs proper investigating or refactoring.

**Comment by hpvd** [comment]
in backend there is no error message visible.
Looks "working ok"
=> is it ok in this installation?
=> or should one add a error massage?
please see attachment (piwik 2.16b3)

![2016-01-18_23h06_34](https://cloud.githubusercontent.com/assets/5681880/12404028/7c8011b4-be38-11e5-880a-ebd8507d2a93.png)

**Comment by clauso** [comment]
I have the same error today (I think I have seen it in the past):

> ERROR [2016-02-03 00:05:11] /var/www/piwik/plugins/UserCountry/GeoIPAutoUpdater.php(161): GeoIPAutoUpdater: failed to unzip '/var/www/piwik/misc/GeoIPCity.dat.dat.gz' after downloading 'http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz': The downloaded file is not a valid GeoIP database. Please re-check the URL or download the file manually.

We are running piwik 2.15.0

I have this md5sum for the downloaded file:
```
$> md5sum /var/www/piwik/misc/GeoLiteCity.dat
97752fa1e1407d9c2c48008a4b9428c1  /var/www/piwik/misc/GeoLiteCity.dat
```

**Comment by nd2s** [comment]
Fails here as well. v2.16.0 on FreeBSD.

**Comment by clauso** [comment]
Still get those mails about failures so I tried to look into it. I found out that I can trigger an update run manually by calling
```
php /var/www/piwik/console scheduled-tasks:run --force
```

A maybe interesting thing is that here I get an additional error that was not in the mails, see line 2:
```
INFO [2016-07-13 04:59:50] GeoIPAutoUpdater: successfully downloaded 'http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz'
INFO [2016-07-13 04:59:50] GeoIPAutoUpdater: Encountered PHP error when testing newly downloaded GeoIP database: 2: include(): Failed opening '/var/www/piwik/tmp/cache/tracker/piwikcache_Translations-en-e21bf04aeec884480f77854677fd2bf5fbc090f3.php' for inclusion (include_path='/var/www/piwik/vendor/pear/pear_exception:/var/www/piwik/vendor/pear/console_getopt:/var/www/piwik/vendor/pear/pear-core-minimal/src:/var/www/piwik/vendor/pear/archive_tar:.:/usr/share/php') on line 112 of /var/www/piwik/vendor/doctrine/cache/lib/Doctrine/Common/Cache/PhpFileCache.php.
ERROR [2016-07-13 04:59:50] /var/www/piwik/plugins/UserCountry/GeoIPAutoUpdater.php(161): GeoIPAutoUpdater: failed to unzip '/var/www/piwik/misc/GeoIPCity.dat.dat.gz' after downloading 'http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz': The downloaded file is not a valid GeoIP database. Please re-check the URL or download the file manually.
```
I currently do not have the piwik knowledge and time to investigate further but maybe this give the right person a hint?

**Comment by jonroberts-anr** [comment]
I blame Cloudflare.  On my server I tried to wget and curl the url manually.
wget gives me this:
Connecting to geolite.maxmind.com (geolite.maxmind.com)|104.16.38.47|:80... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2017-05-14 00:09:56 ERROR 503: Service Temporarily Unavailable.

curl gives me this:
<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif; font-size: 100%;}
    h1 {font-size: 1.5em; color: #404040; text-align: center;}
    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 20px;}
    @-webkit-keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    @keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0); } }
    .bubbles { background-color: #404040; width:15px; height: 15px; margin:2px; border-radius:100%; -webkit-animation:bubbles 0.6s 0.07s infinite ease-in-out; animation:bubbles 0.6s 0.07s infinite ease-in-out; -webkit-animation-fill-mode:both; animation-fill-mode:both; display:inline-block; }
  </style>

    <script type="text/javascript">
  //<![CDATA[
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var a = document.getElementById('cf-content');a.style.display = 'block';
      setTimeout(function(){
        var s,t,o,p,b,r,e,a,k,i,n,g,f, YCbBnNK={"D":+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]))};
        t = document.createElement('div');
        t.innerHTML="<a href='/'>x</a>";
        t = t.firstChild.href;r = t.match(/https?:\/\//)[0];
        t = t.substr(r.length); t = t.substr(0,t.length-1);
        a = document.getElementById('jschl-answer');
        f = document.getElementById('challenge-form');
        ;YCbBnNK.D-=+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]));YCbBnNK.D+=+((+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));YCbBnNK.D*=!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![];a.value = parseInt(YCbBnNK.D, 10) + t.length; '; 121'
        f.submit();
      }, 4000);
    }, false);
  })();
  //]]>
</script>


</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1></noscript>
  <div id="cf-content" style="display:none">
    
    <div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> maxmind.com.</h1>
    
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>
  </div>
   
  <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get">
    <input type="hidden" name="jschl_vc" value="03088e7bd9d6439689f841dffccd3f7b"/>
    <input type="hidden" name="pass" value="1494720091.825-bErpG0+Bvg"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
</div>

          
          <div class="attribution">
            <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=iuam" target="_blank" style="font-size: 12px;">DDoS protection by Cloudflare</a>
            <br>
            Ray ID: 35e99544e3061049
          </div>
      </td>
     
    </tr>
  </table>
</body>
</html>

**Comment by robertoschwald** [comment]
Any news on this? Facing this problem since a long time

**Comment by JonTheWong** [comment]
I've been recently getting the same error.
My current error output is for GeoLite2 but I've tried legacy with no success. The URL is giving me a 404 on legacy. Geo2 doesn't work because it doesn't contain a .dat file.

System Check
"Huzzah! There are no problems with your Matomo setup. Give yourself a pat on the back."

Matomo 3.7.0 Current.

```
ERROR [2019-01-13 11:49:21] 6701  /home/user/public_html/analytics.example.com/plugins/UserCountry/GeoIPAutoUpdater.php(167): GeoIPAutoUpdater: failed to unzip '/home/user/public_html/analytics.example.com/misc/GeoIPCity.dat.tar.gz' after downloading 'https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz': Cannot find GeoIPCity.dat file in tar archive '/home/user/public_html/analytics.example.com/misc/GeoIPCity.dat.tar.gz'!
#0 /home/user/public_html/analytics.example.com/plugins/UserCountry/GeoIPAutoUpdater.php(102): Piwik\Plugins\UserCountry\GeoIPAutoUpdater->downloadFile('loc', 'https://geolite...')
#1 [internal function]: Piwik\Plugins\UserCountry\GeoIPAutoUpdater->update(NULL)
#2 /home/user/public_html/analytics.example.com/core/Scheduler/Scheduler.php(246): call_user_func(Array, NULL)
#3 /home/user/public_html/analytics.example.com/core/Scheduler/Scheduler.php(136): Piwik\Scheduler\Scheduler->executeTask(Object(Piwik\Plugins\UserCountry\GeoIPAutoUpdater))
#4 /home/user/public_html/analytics.example.com/plugins/CoreAdminHome/API.php(58): Piwik\Scheduler\Scheduler->run()
#5 /home/user/public_html/analytics.example.com/core/CronArchive.php(612): Piwik\Plugins\CoreAdminHome\API->runScheduledTasks()
#6 /home/user/public_html/analytics.example.com/core/CronArchive.php(317): Piwik\CronArchive->runScheduledTasks()
#7 /home/user/public_html/analytics.example.com/core/Access.php(626): Piwik\CronArchive->Piwik\{closure}()
#8 /home/user/public_html/analytics.example.com/core/CronArchive.php(319): Piwik\Access::doAsSuperUser(Object(Closure))
#9 /home/user/public_html/analytics.example.com/plugins/CoreConsole/Commands/CoreArchiver.php(27): Piwik\CronArchive->main()
#10 /home/user/public_html/analytics.example.com/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreConsole\Commands\CoreArchiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/user/public_html/analytics.example.com/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/user/public_html/analytics.example.com/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\CoreConsole\Commands\CoreArchiver), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/user/public_html/analytics.example.com/core/Console.php(90): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/user/public_html/analytics.example.com/core/Access.php(626): Piwik\Console->Piwik\{closure}()
#16 /home/user/public_html/analytics.example.com/core/Console.php(91): Piwik\Access::doAsSuperUser(Object(Closure))
#17 /home/user/public_html/analytics.example.com/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/user/public_html/analytics.example.com/console(27): Symfony\Component\Console\Application->run()
#19 {main}
```

Found the original log.

```
ERROR [2019-01-09 11:45:50] 12232  /home/user/public_html/analytics.example.com/plugins/UserCountry/GeoIPAutoUpdater.php(167): GeoIPAutoUpdater: failed to unzip '/home/user/public_html/analytics.example.com/misc/GeoIPCity.dat.dat.gz' after downloading 'http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz': The downloaded file is not a valid GeoIP database. Please re-check the URL or download the file manually.
#0 /home/user/public_html/analytics.example.com/plugins/UserCountry/GeoIPAutoUpdater.php(102): Piwik\Plugins\UserCountry\GeoIPAutoUpdater->downloadFile('loc', 'http://geolite....')
#1 [internal function]: Piwik\Plugins\UserCountry\GeoIPAutoUpdater->update(NULL)
#2 /home/user/public_html/analytics.example.com/core/Scheduler/Scheduler.php(246): call_user_func(Array, NULL)
#3 /home/user/public_html/analytics.example.com/core/Scheduler/Scheduler.php(136): Piwik\Scheduler\Scheduler->executeTask(Object(Piwik\Plugins\UserCountry\GeoIPAutoUpdater))
#4 /home/user/public_html/analytics.example.com/plugins/CoreAdminHome/API.php(58): Piwik\Scheduler\Scheduler->run()
#5 /home/user/public_html/analytics.example.com/core/CronArchive.php(612): Piwik\Plugins\CoreAdminHome\API->runScheduledTasks()
#6 /home/user/public_html/analytics.example.com/core/CronArchive.php(317): Piwik\CronArchive->runScheduledTasks()
#7 /home/user/public_html/analytics.example.com/core/Access.php(626): Piwik\CronArchive->Piwik\{closure}()
#8 /home/user/public_html/analytics.example.com/core/CronArchive.php(319): Piwik\Access::doAsSuperUser(Object(Closure))
#9 /home/user/public_html/analytics.example.com/plugins/CoreConsole/Commands/CoreArchiver.php(27): Piwik\CronArchive->main()
#10 /home/user/public_html/analytics.example.com/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreConsole\Commands\CoreArchiver->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/user/public_html/analytics.example.com/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/user/public_html/analytics.example.com/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\CoreConsole\Commands\CoreArchiver), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/user/public_html/analytics.example.com/core/Console.php(90): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/user/public_html/analytics.example.com/core/Access.php(626): Piwik\Console->Piwik\{closure}()
#16 /home/user/public_html/analytics.example.com/core/Console.php(91): Piwik\Access::doAsSuperUser(Object(Closure))
#17 /home/user/public_html/analytics.example.com/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/user/public_html/analytics.example.com/console(27): Symfony\Component\Console\Application->run()
#19 {main}
```

**Comment by OliverTempel** [comment]
Same Error Here.

**Comment by OliverTempel** [comment]
MaxMind has changed downloads.
New Files has MaxMind Database Format, so no .dat file is included in download.
